export type CraftsmanOrderStatus = 
  | 'REQUESTED'
  | 'ACCEPTED'
  | 'EN_ROUTE'
  | 'ARRIVED'
  | 'OTP_STARTED'
  | 'IN_PROGRESS'
  | 'PARTS_PENDING'
  | 'OTP_COMPLETED'
  | 'REVIEWED'
  | 'DISPUTED'
  | 'CANCELLED';

export type ServiceEmergencyCategory = 
  | 'plumbing_leak'
  | 'electrical_outage'
  | 'locksmith_locked_out'
  | 'ac_heating_failure'
  | 'gas_leak_safety'
  | 'roof_drainage_emergency';

export interface SparePartItem {
  id: string;
  name: string;
  nameAr: string;
  priceDA: number;
  quantity: number;
  receiptPhotoUrl?: string;
  receiptThumbnail?: string;
  addedAt: string;
  status: 'pending_approval' | 'approved' | 'rejected';
  rejectionReason?: string;
}

export interface QuotationDetails {
  laborType: 'fixed_quote' | 'hourly_rate';
  laborCostDA: number;
  estimatedHours?: number;
  spareParts: SparePartItem[];
  emergencySurgeFeeDA: number;
  platformCommissionRate: number; // e.g. 0.05 (5%)
  vatRate: number; // e.g. 0
}

export interface JobVerificationPhotos {
  beforePhotoUrl?: string;
  beforeTimestamp?: string;
  beforeNotes?: string;
  afterPhotoUrl?: string;
  afterTimestamp?: string;
  afterNotes?: string;
  showcaseInPortfolio: boolean;
  customerAnonymityConfirmed: boolean;
}

export interface OtpSecurityState {
  startOtp: string; // 4-digit code generated by customer
  startOtpEntered: string;
  startOtpAttempts: number;
  isStartOtpVerified: boolean;
  completionOtp: string; // 4-digit code generated by customer
  completionOtpEntered: string;
  completionOtpAttempts: number;
  isCompletionOtpVerified: boolean;
  isLockedOut: boolean;
  lockoutReason?: string;
}

export interface CustomerEvaluation {
  rating: number; // 1-5
  chips: {
    punctuality: boolean;
    cleanliness: boolean;
    technicalSkill: boolean;
    pricingTransparency: boolean;
  };
  comment: string;
  evidencePhotoUrl?: string;
  submittedAt?: string;
}

export interface CraftsmanEvaluation {
  rating: number; // 1-5
  chips: {
    safetyAndRespect: boolean;
    paymentPromptness: boolean;
    workEnvironmentSafe: boolean;
    clearInstructions: boolean;
  };
  comment: string;
  submittedAt?: string;
}

export interface MutualReviewState {
  customerReview?: CustomerEvaluation;
  craftsmanReview?: CraftsmanEvaluation;
  isRevealed: boolean; // double-blind reveal
  revealedAt?: string;
}

export interface CraftsmanOrder {
  id: string;
  serviceTitleAr: string;
  serviceTitleEn: string;
  category: ServiceEmergencyCategory;
  isEmergency: boolean;
  emergencyRadiusKm: number;
  customer: {
    id: string;
    name: string;
    phone: string;
    maskedPhone: string;
    wilaya: string;
    address: string;
    maskedAddress: string;
    avatarUrl: string;
    rating: number;
  };
  craftsman: {
    id: string;
    name: string;
    phone: string;
    avatarUrl: string;
    badge: 'Top Rated Pro' | 'Verified Craftsman' | 'Master Handyman';
    rating: number;
    completedJobsCount: number;
    currentDistanceKm: number;
    estimatedArrivalMinutes: number;
    specialtyAr: string;
    specialtyEn: string;
  };
  status: CraftsmanOrderStatus;
  quotation: QuotationDetails;
  verificationPhotos: JobVerificationPhotos;
  otpSecurity: OtpSecurityState;
  reviews: MutualReviewState;
  createdAt: string;
  updatedAt: string;
}
