'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  FileText, Download, Calendar, BarChart3, TrendingUp, 
  FileSpreadsheet, Sparkles, RefreshCw, Eye, CheckCircle2
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { adminDataService, AdminReport } from '@/services/adminDataService';
import { AdminDataTable, ColumnDef, FilterOption } from '@/components/admin/shared/AdminDataTable';
import { AdminDetailDrawer } from '@/components/admin/shared/AdminDetailDrawer';

export function PlatformReportsSection() {
  const { toast } = useToast();
  const [reports, setReports] = useState<AdminReport[]>([]);
  const [selectedReport, setSelectedReport] = useState<AdminReport | null>(null);
  const [isDetailOpen, setIsDetailOpen] = useState(false);

  const loadData = () => {
    setReports(adminDataService.getReports());
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleDownloadReport = (rep: AdminReport) => {
    toast({
      title: 'Report Download Started',
      description: `Downloading ${rep.reportName} (${rep.format.toUpperCase()}).`,
    });
  };

  const handleGenerateOnDemand = (type: string) => {
    const newRep: AdminReport = {
      id: `rep_${Date.now()}`,
      reportName: `Real-Time ${type} Summary - ${new Date().toLocaleDateString()}`,
      category: 'financial',
      format: 'xlsx',
      period: 'daily',
      generatedDate: new Date().toISOString().replace('T', ' ').substring(0, 19),
      fileSize: '1.8 MB',
      generatedBy: 'Super Admin',
      summaryMetrics: {
        totalRevenue: 4500000,
        commissionCollected: 410000,
        totalOrders: 215,
        newUsers: 64,
      },
    };
    const updated = [newRep, ...reports];
    adminDataService.saveReports(updated);
    adminDataService.recordAudit('Super Admin', 'CREATE', 'Report', newRep.id, `Generated on-demand ${type} report`);
    setReports(updated);
    toast({
      title: 'Report Generated',
      description: `${newRep.reportName} is ready for download.`,
    });
  };

  const filterOptions: FilterOption[] = [
    {
      key: 'category',
      label: 'Category',
      options: [
        { label: 'Financial', value: 'financial' },
        { label: 'Sales & Logistics', value: 'sales' },
        { label: 'Logistics', value: 'logistics' },
        { label: 'User Growth', value: 'users' },
      ],
    },
    {
      key: 'period',
      label: 'Period',
      options: [
        { label: 'Daily', value: 'daily' },
        { label: 'Weekly', value: 'weekly' },
        { label: 'Monthly', value: 'monthly' },
        { label: 'Quarterly', value: 'quarterly' },
      ],
    },
  ];

  const columns: ColumnDef<AdminReport>[] = [
    {
      header: 'Report Title',
      accessorKey: 'reportName',
      cell: (r) => (
        <div className="space-y-0.5">
          <div className="font-semibold text-foreground flex items-center gap-1.5">
            <FileSpreadsheet className="h-4 w-4 text-primary shrink-0" />
            {r.reportName}
          </div>
          <div className="text-xs text-muted-foreground">Generated by: {r.generatedBy}</div>
        </div>
      ),
    },
    {
      header: 'Category & Period',
      accessorKey: 'category',
      cell: (r) => (
        <div className="space-y-0.5 text-xs">
          <Badge variant="outline" className="bg-muted/40 font-normal uppercase text-[10px]">
            {r.category}
          </Badge>
          <div className="text-muted-foreground capitalize">{r.period}</div>
        </div>
      ),
    },
    {
      header: 'File Format & Size',
      accessorKey: 'format',
      cell: (r) => (
        <div className="text-xs">
          <Badge variant="secondary" className="font-mono uppercase text-[10px] font-bold">
            .{r.format}
          </Badge>
          <span className="text-muted-foreground ml-1.5">{r.fileSize}</span>
        </div>
      ),
    },
    {
      header: 'Generated Date',
      accessorKey: 'generatedDate',
      cell: (r) => <span className="text-xs text-muted-foreground">{r.generatedDate}</span>,
    },
    {
      header: 'Actions',
      cell: (r) => (
        <div className="flex items-center gap-1.5" onClick={(e) => e.stopPropagation()}>
          <Button
            size="sm"
            variant="outline"
            className="h-8 px-2.5 text-xs"
            onClick={() => handleDownloadReport(r)}
          >
            <Download className="h-3.5 w-3.5 mr-1" /> Download
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-8 px-2 text-xs"
            onClick={() => {
              setSelectedReport(r);
              setIsDetailOpen(true);
            }}
          >
            <Eye className="h-3.5 w-3.5" />
          </Button>
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold font-headline flex items-center tracking-tight">
            <FileText className="mr-3 h-8 w-8 text-primary" /> Reports & Analytics Exports
          </h1>
          <p className="text-muted-foreground text-sm">
            Generate and download scheduled financial statements, tax reporting records, logistics KPIs, and user metrics.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button onClick={() => handleGenerateOnDemand('Financial & P&L')} className="h-10 px-4 rounded-xl font-medium">
            <Sparkles className="h-4 w-4 mr-2" /> Generate Real-Time Statement
          </Button>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card className="bg-card shadow-sm">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-muted-foreground">Available Reports</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">{reports.length}</div>
            <p className="text-xs text-muted-foreground mt-1">Archived in cloud storage</p>
          </CardContent>
        </Card>
        <Card className="bg-card shadow-sm">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-muted-foreground">Automated Cron</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-emerald-600">Daily / Monthly</div>
            <p className="text-xs text-muted-foreground mt-1">Midnight automated run</p>
          </CardContent>
        </Card>
        <Card className="bg-card shadow-sm">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-muted-foreground">Tax Statement Status</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-primary">Compliant</div>
            <p className="text-xs text-muted-foreground mt-1">Algerian 19% TVA tracked</p>
          </CardContent>
        </Card>
        <Card className="bg-card shadow-sm">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-muted-foreground">Export Formats</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">CSV, XLSX, PDF</div>
            <p className="text-xs text-muted-foreground mt-1">Universal compatibility</p>
          </CardContent>
        </Card>
      </div>

      {/* Table */}
      <AdminDataTable
        data={reports}
        columns={columns}
        searchPlaceholder="Search reports by title, category, author..."
        searchKeys={['reportName', 'category', 'period', 'generatedBy']}
        filterOptions={filterOptions}
        exportFileName="khidmatik_reports_index"
        onRowClick={(r) => {
          setSelectedReport(r);
          setIsDetailOpen(true);
        }}
        onRefresh={loadData}
      />

      {/* Detail Drawer */}
      {selectedReport && (
        <AdminDetailDrawer
          isOpen={isDetailOpen}
          onClose={() => setIsDetailOpen(false)}
          title={selectedReport.reportName}
          subtitle={`Generated: ${selectedReport.generatedDate} • Size: ${selectedReport.fileSize}`}
          statusBadge={{
            label: selectedReport.format.toUpperCase(),
            variant: 'default',
          }}
          metrics={[
            { label: 'File Size', value: selectedReport.fileSize, icon: FileText },
            { label: 'Category', value: selectedReport.category.toUpperCase(), icon: BarChart3 },
            { label: 'Schedule', value: selectedReport.period.toUpperCase(), icon: Calendar },
            { label: 'Author', value: selectedReport.generatedBy, icon: Sparkles },
          ]}
          fields={[
            { label: 'Report Name', value: selectedReport.reportName, fullWidth: true },
            { label: 'Generated Timestamp', value: selectedReport.generatedDate },
            { label: 'Generated Operator', value: selectedReport.generatedBy },
            { label: 'File Format', value: `.${selectedReport.format.toUpperCase()}` },
            { label: 'Report Period', value: selectedReport.period.toUpperCase() },
          ]}
          actions={
            <Button onClick={() => handleDownloadReport(selectedReport)} size="sm">
              <Download className="h-4 w-4 mr-1.5" /> Download Report File
            </Button>
          }
        />
      )}
    </div>
  );
}
