
'use client';

import type { Language, LanguageContextType } from '@/types';
import React, { createContext, useState, useContext, useEffect, type ReactNode } from 'react';

// Basic translations store
const translations: Record<Language, Record<string, string>> = {
  en: {
    stores: 'Stores',
    services: 'Services',
    digital: 'Digital',
    marketplace: 'Marketplace',
    profileMenu: 'Profile Menu',
    myAccount: 'My Account',
    profile: 'Profile',
    dashboards: 'Dashboards',
    myStoreDashboard: 'My Store Dashboard',
    servicesAdminPanel: 'Services Admin Panel',
    platformSuperAdmin: 'Platform Super Admin',
    logOut: 'Log Out',
    notifications: 'Notifications',
    recentActivityAlertsUpdates: 'Recent activity, alerts, and updates.',
    viewAllNotifications: 'View All Notifications',
    selectLanguage: 'Select Language',
    english: 'English',
    arabic: 'العربية (Arabic)',
    french: 'Français (French)',
    logIn: 'Log In',
    register: 'Register',
    welcomeToKhidmatik: 'Welcome to Khidmatik',
    welcomeSubtitle: 'Your Super-App for Algérie! Discover stores, services, parts, and more.',
    browseByCategory: 'Browse by Category',
    viewAllListings: 'View All Categories & Listings',
    featuredListings: 'Featured Listings',
    madeInAlgeria: 'Proudly Made in Algérie',
    exploreAllLocal: 'Explore All Local Products',
    areYouBusinessOwner: 'Are you a Business Owner or Professional?',
    joinKhidmatikToday: 'Join Khidmatik today and reach more customers in your area.',
    listYourBusiness: 'List Your Business or Service',
    footerRights: 'Khidmatik. All rights reserved.',
    footerSlogan: 'Connecting communities in Algérie, one click at a time.',
    appRoadmap: 'App Roadmap',
    servicePoint: 'Service Point',
    
    // Marketplace & Parts Mine
    marketplaceTitle: 'Welcome to the Marketplace',
    marketplaceSub: 'Your specialized hub for buying and selling new & used spare parts in Algérie.',
    partsMineTitle: 'Welcome to The Parts Mine',
    partsMineSub: 'Your specialized marketplace for buying and selling new & used spare parts.',
    listPartBtn: 'List a Part for Sale',
    requestPartBtn: 'Request a Missing Part',
    findSpareParts: 'Find Spare Parts',
    findSparePartsDesc: 'Search by part name, device model, or use the filters below.',
    searchPlaceholderParts: 'Search for part name, device model...',
    filterCategory: 'Filter by Category...',
    allCategories: 'All Categories',
    filterCondition: 'Filter by Condition...',
    allConditions: 'All Conditions',
    filterWilaya: 'Filter by Wilaya...',
    allWilayas: 'All Wilayas',
    searchKeywordPlaceholder: 'Keyword (e.g., pizza, plumber)',
    locationPlaceholder: 'Location (e.g., Alger Centre)',
    searchBtn: 'Search',
    advancedFilters: 'Advanced Filters',
    capacityLabel: 'Minimum Capacity',
    capacityPlaceholder: 'Capacity (e.g., 100)',
    priceLabel: 'Maximum Budget (DA)',
    pricePlaceholder: 'Price (e.g., 1000)',
    dateLabel: 'Preferred Date',
    selectDate: 'Select Date',
    myServices: 'My Services',
    manageServicesDesc: 'Add, edit, and manage the services you offer to clients.',
    addNewServiceBtn: 'Add New Service',
    serviceListingsTitle: 'Your Service Listings',
    serviceListingsDesc: 'Overview of your currently offered services.',
    searchServicesPlaceholder: 'Search services...',
    filterBtn: 'Filter',
    filterAll: 'All',
    filterActive: 'Active',
    filterDraft: 'Draft',
    tableNameHeader: 'Service Name',
    tableCategoryHeader: 'Category',
    tablePriceHeader: 'Base Price',
    tableStatusHeader: 'Status',
    tableActionsHeader: 'Actions',
    noServicesAdded: "You haven't added any services yet.",
    editServiceTitle: 'Edit Service',
    addNewServiceTitle: 'Add New Service',
    serviceDetailsDesc: 'Provide detailed information about the service you offer.',
    formServiceNameLabel: 'Service Name / Title *',
    formServiceDescriptionLabel: 'Detailed Description *',
    formServiceCategoryLabel: 'Service Category *',
    formBasePriceLabel: 'Base Price (DA)',
    formPriceUnitLabel: 'Price Unit (Optional)',
    pricingOptionsTitle: 'Pricing Options *',
    addCustomPricingBtn: '+ Add Customizable Pricing Options',
    deliveryTimeLabel: 'Estimated Delivery Time / Duration',
    deliveryScheduleTitle: 'Delivery & Schedule',
    setDeliveryScheduleBtn: '+ Set Delivery Schedule Options',
    mediaSectionTitle: 'Media (Images, Videos, PDFs)',
    uploadImagesBtn: 'Upload Images (max 5)',
    addVideoLinkBtn: 'Add Video Link (YouTube, Vimeo)',
    uploadPdfBtn: 'Upload PDF Samples/Brochures',
    serviceBundlesTitle: 'Service Bundles / Packages',
    serviceBundlesDesc: 'Offer combined services at a special price.',
    createBundleBtn: 'Create Service Bundle',
    cancelBtn: 'Cancel',
    saveServiceBtn: 'Save Service',
    toastServiceCreated: 'Service Created',
    toastServiceUpdated: 'Service Updated',
    toastServiceSavedDesc: 'Service details saved successfully.',
    toastServiceDeleted: 'Service Deleted',
    toastServiceDeletedDesc: 'The service has been removed.',
    recentlyListed: 'Recently Listed Parts',
    noPartsFound: 'No parts match your current search/filters.',
    noPartsFoundSub: 'Try adjusting your search or view all available parts.',
    aiDiscovery: 'AI-Powered Discovery',
    aiDiscoverySub: 'Our AI helps you find what you need!',
    smartRequestMatching: 'Smart Request Matching',
    smartRequestMatchingDesc: 'When you request a part, our AI searches listings and notifies you of matches. Sellers may also be notified.',
    enhancedSearch: 'Enhanced Search (Coming Soon)',
    enhancedSearchDesc: 'AI will suggest compatible or alternative parts.',
    exampleAiSuggestion: 'Example AI Suggestion (Conceptual):',
    exampleAiText: '"We noticed you recently requested a refrigerator technician. You might be interested in these refrigerator parts..."',
    activeRequests: 'My Active Part Requests',
    secureTransactions: 'Secure Transactions',
    secureTransactionsDesc: 'All transactions within the Marketplace/Parts Mine are designed with your security in mind.',
    inAppComm: 'In-App Communication',
    inAppCommDesc: 'Chat securely with sellers/buyers to discuss details and arrange delivery.',
    escrowWallet: 'Escrow Wallet Protection',
    escrowWalletDesc: 'Payments are processed through Escrow Wallet. Funds are held until you confirm receipt.',
    disputeRes: 'Dispute Resolution',
    disputeResDesc: 'A simple mechanism for dispute resolution will be available to help with any issues.',
    advancedFiltersSoon: 'Advanced filters for brand and price range coming soon.',

    // Digital Services
    digitalServicesTitle: 'Digital Services',
    exploreDigitalServices: 'Explore Digital Services',
    findFreelancersSub: 'Find local freelancers and digital service providers in Algérie.',
    searchFreelancerPlaceholder: 'Search by name, skill, service...',
    allDigitalCategories: 'All Digital Categories',
    searchDigitalBtn: 'Search Digital Services',
    noFreelancersFound: 'No Digital Service Providers Found',
    noFreelancersFoundSub: "We couldn't find any freelancers matching your criteria. Try adjusting your search or filters.",
    clearFiltersBtn: 'Clear Filters and Search Again',

    // Dashboards & Sidebar
    storeDashboard: 'Store Dashboard',
    overview: 'Overview / Dashboard',
    ordersReturns: 'All Orders',
    productsInventory: 'Products & Inventory',
    customersReviews: 'Customers & Reviews',
    marketingPromotions: 'Marketing & Promotions',
    financialsPayouts: 'Financials',
    aiSellerAssistant: 'AI Seller Assistant',
    analyticsReports: 'Analytics & Reports',
    storeSettingsConfig: 'Store Settings & Config',
    suppliers: 'Suppliers',
    backToMainSite: 'Back to Main Site',
    scheduledOrders: 'Scheduled Orders',
    newOrder: 'New Order',
    failureManagement: 'Failure Management',
    stockInventory: 'Stock & Inventory',
    salesChannels: 'Sales Channels',
    dispatchOrders: 'Order Dispatch',
    payments: 'Payments',
    teamManagement: 'Team & Access',
    deliverySettings: 'Delivery Settings',
    webhooks: 'Webhooks & Dev Tools',
    adminDashboard: 'Super Admin',
    verificationQueue: 'Verification Queue',
    userManagement: 'User Management',
    storeManagement: 'Store Dashboard',
    reservationManagement: 'Reservations',
    providerManagement: 'Services Admin Panel',
    financialManagement: 'Payments & Subscriptions',
    platformAnalytics: 'Reports & Statistics',
    contentModeration: 'Content Moderation',
    cmsSiteContent: 'Templates & CMS',
    systemConfiguration: 'General Settings',
    securityAudit: 'Logs, Backups & Maintenance',
    aiAdvancedTools: 'Plugins & APIs',
    supportSystem: 'Support & Tickets',
    myProfile: 'My Profile',
    actions: 'Actions',
    settings: 'Settings',
    security: 'Security',
    accountSettings: 'Account Settings',
    notificationCenter: 'Notification Center',
    securityPassword: 'Security & Password',
    language: 'Language',
    appearance: 'Appearance',
    sessionsDevices: 'Sessions & Devices',
    activityLog: 'Activity Log',
    favorites: 'Favorites',
    savedItems: 'Saved Items',
    myFiles: 'My Files',
    messages: 'Messages',
    lastLogin: 'Last Login',
    accountStatus: 'Account Status',
    subscriptionType: 'Subscription Type',
    accountCreated: 'Account Created',
    phone: 'Phone',
    emailVerified: 'Email Verified',
    phoneVerified: 'Phone Verified',
    markAllRead: 'Mark all as read',
    notificationPref: 'Notification Preferences',
    emailNotifications: 'Email Notifications',
    pushNotifications: 'Push Notifications',
    changePassword: 'Change Password',
    twoFactorAuth: 'Two-Factor Authentication (2FA)',
    loginHistory: 'Login History',
    activeSessions: 'Active Sessions',
    trustedDevices: 'Trusted Devices',
    apiTokens: 'API Tokens',
    theme: 'Theme',
    fontSize: 'Font Size',
    changeAvatar: 'Change Photo',
    quickStats: 'Quick Statistics',
    ordersToday: 'Orders Today',
    storesCount: 'Stores',
    servicesCount: 'Services',
    pendingTickets: 'Pending Tickets',
    revenueToday: 'Revenue Today',
    newUsers: 'New Users',
    logoutAllDevices: 'Logout from all devices',
    logoutConfirm: 'Are you sure you want to log out?',
    logoutConfirmDesc: 'You will be signed out of your current session.',
    logoutCurrent: 'Logout Current Session',
    active: 'Active',
    yes: 'Yes',
    no: 'No',
    verified: 'Verified',

    // Professional Dashboard Additions
    publicProfile: 'Public Profile',
    verificationBadges: 'Verification & Badges',
    serviceManagement: 'Service Management',
    bookingsCalendar: 'Bookings & Calendar',
    projectsOrders: 'Projects & Orders',
    earningsPayouts: 'Earnings & Payouts',
    clientCommunication: 'Client Communication',
    performanceAnalytics: 'Performance Analytics',
    settingsIntegrations: 'Settings & Integrations',
    helpSupport: 'Help & Support',
    servicesAdmin: 'Services Admin',

    // Dashboard Sections - Bookings
    manageAppointments: 'Manage your appointments, availability, and client bookings.',
    addAppointment: 'Add Appointment',
    myCalendar: 'My Calendar',
    manageAvailability: 'Manage Availability',
    appointmentsFor: 'Appointments for',
    today: 'Today',
    reviewAppointments: 'Review and manage your scheduled appointments for the selected date.',
    time: 'Time',
    client: 'Client',
    service: 'Service',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    pending: 'Pending',
    noAppointments: 'No appointments scheduled for this date.',
    scheduleNewAppointment: 'Schedule a new appointment with a client.',
    clientName: 'Client Name',
    notes: 'Notes',
    optionalNotes: 'Optional notes...',
    appointmentDetails: 'Appointment Details',
    appointmentAdded: 'Appointment Added',
    appointmentAddedDesc: 'New appointment has been scheduled.',
    appointmentConfirmed: 'Appointment Confirmed',
    appointmentCancelled: 'Appointment Cancelled',
    setWorkingHours: 'Set your working hours and buffer time between appointments.',
    startHour: 'Start Hour',
    endHour: 'End Hour',
    bufferTime: 'Buffer Time (minutes)',
    availabilitySaved: 'Availability Saved',
    availabilitySavedDesc: 'Your working hours have been updated.',
    close: 'Close',

    // Dashboard Sections - Projects
    trackProjects: 'Track ongoing services, client projects, and order statuses.',
    currentProjects: 'Current Projects/Orders',
    manageProgress: 'Manage the progress and status of your client engagements.',
    searchProjects: 'Search by Client or Service Name...',
    filterByStatus: 'Filter by Status',
    inProgress: 'In Progress',
    completed: 'Completed',
    scheduled: 'Scheduled',
    awaitingFeedback: 'Awaiting Client',
    rejected: 'Rejected',
    projectId: 'Project ID',
    deadline: 'Deadline',
    payment: 'Payment',
    noProjects: 'No active projects or orders.',
    quickActions: 'Quick Actions',
    markCompleted: 'Mark as Completed',
    requestRevision: 'Request Revision',
    cancelOrder: 'Cancel Order',
    sendUpdate: 'Send Update',
    projectDetails: 'Project Details',
    statusUpdated: 'Status Updated',
    projectStatus: 'Project status changed to',
    sendUpdateToClient: 'Send Update to Client',
    typeUpdate: 'Type your update message...',
    updateSent: 'Update Sent',
    updateSentTo: 'Update sent to client for project',

    // Dashboard Sections - Communication
    manageCommunication: 'Manage messages, track conversations, and stay connected with your clients.',
    myConversations: 'My Conversations',
    searchMessages: 'Search...',
    selectConversation: 'Select a conversation to start messaging.',
    realtimeMessaging: 'Real-time messaging with your client.',
    typeMessage: 'Type your message...',
    messageSent: 'Message Sent',
    conversationArchived: 'Conversation Updated',
    noConversations: 'No conversations.',

    // Dashboard Sections - Marketing
    boostVisibility: 'Boost your visibility and attract more clients with promotional tools.',
    discountCoupons: 'Discount Coupons & Promo Codes',
    createManageCoupons: 'Create and manage discount codes for your services.',
    couponCode: 'Coupon Code',
    discountType: 'Discount Type',
    percentage: 'Percentage (%)',
    fixedAmount: 'Fixed Amount (DA)',
    valueAmount: 'Value / Amount',
    expiryDate: 'Expiry Date (Optional)',
    usageLimit: 'Usage Limit (0 = unlimited)',
    createCoupon: 'Create Coupon',
    existingCoupons: 'Existing Coupons',
    code: 'Code',
    discount: 'Discount',
    usage: 'Usage',
    expired: 'Expired',
    couponCreated: 'Coupon Created',
    couponDeleted: 'Coupon Deleted',
    clientTargeting: 'Client Targeting',
    clientTargetingDesc: 'Tools to run targeted promotions to specific client segments.',

    // Dashboard Sections - Earnings
    trackEarnings: 'Track your earnings, manage invoices, and request withdrawals.',
    totalEarned: 'Total Earned',
    pendingPayout: 'Pending Payout',
    platformFees: 'Platform Fees',
    netEarnings: 'Net Earnings',
    transactionHistory: 'Transaction History & Invoices',
    viewPayments: 'View all payments, commissions, and generate invoices.',
    description: 'Description',
    type: 'Type',
    amount: 'Amount (DA)',
    invoice: 'Invoice',
    exportData: 'Export Earnings Data',
    withdrawalSystem: 'Withdrawal System',
    requestPayouts: 'Request payouts to your bank account or other supported methods.',
    currentMethod: 'Current Payout Method',
    requestWithdrawal: 'Request New Withdrawal',
    managePayoutMethods: 'Manage Payout Methods',
    commissionNote: 'Platform commissions are automatically calculated and deducted before payouts. Standard payout processing time is 3-5 business days.',
    enterWithdrawAmount: 'Enter the amount you wish to withdraw.',
    payoutMethod: 'Payout Method',
    selectMethod: 'Select method...',
    submitWithdrawal: 'Submit Withdrawal',
    withdrawalRequested: 'Withdrawal Requested',
    willBeProcessed: 'will be processed in 3-5 business days.',
    addNewMethod: 'Add New Method',
    accountDetails: 'Account details (e.g., account number)',
    addMethod: 'Add Method',
    payoutMethodAdded: 'Payout Method Added',
    exportComplete: 'Export Complete',
    csvDownloaded: 'CSV file has been downloaded.',
    invoiceGenerated: 'Invoice Generated',
    downloaded: 'downloaded',

    // Dashboard Sections - Support
    getHelp: 'Get help, find answers, and manage your support requests.',
    submitRequest: 'Submit a New Support Request',
    needHelp: 'Need help with the platform or have an issue? Let us know.',
    subject: 'Subject',
    category: 'Category',
    selectCategory: 'Select issue category...',
    technicalIssue: 'Technical Issue',
    billingPayment: 'Billing/Payment',
    serviceListing: 'Service Listing',
    accountHelp: 'Account Help',
    other: 'Other',
    describeIssue: 'Describe your issue',
    provideDetails: 'Please provide as much detail as possible...',
    submitTicket: 'Submit Ticket',
    myTickets: 'My Support Tickets',
    trackTickets: 'Track the status of your submitted support requests.',
    searchTickets: 'Search my tickets...',
    ticketId: 'Ticket ID',
    lastUpdate: 'Last Update',
    open: 'Open',
    resolved: 'Resolved',
    viewReply: 'View/Reply',
    noTickets: 'You have no support tickets.',
    knowledgeBase: 'Knowledge Base & FAQs',
    findAnswers: 'Find answers to common questions and learn how to use platform features.',
    ticketSubmitted: 'Ticket Submitted',
    ticketSubmittedDesc: 'Your support request has been sent.',
    originalMessage: 'Original Message',
    you: 'You',
    supportTeam: 'Support Team',
    yourReply: 'Your Reply',
    typeReply: 'Type your reply...',
    sendReply: 'Send Reply',
    replySent: 'Reply Sent',
    justNow: 'Just now',
    ago: 'ago',

    // Reservations
    reservationsTitle: 'Reservations',
    banquetHallsReservations: 'Banquet Halls Reservations',

    // AI Refinements
    aiRefinementsTitle: 'Need Help Refining Your Search?',
    getAiSuggestions: 'Get AI Suggestions',
    generatingSuggestions: 'Generating suggestions...',
    aiRefinementsClickDesc: "Click 'Get AI Suggestions' to see if we can help you narrow down your search results.",
    noRefinementsFound: 'No specific refinements found for the current search.',
    errRefinements: 'Could not fetch AI search refinements. Please try again.',

    // Centralized Notifications
    notificationCenterSub: 'Manage live alerts, order updates, booking statuses, payments, and system notices.',
    notificationPrefSub: 'Customize delivery channels and types of alerts you receive.',
    deliveryChannels: 'Delivery Channels',
    inAppNotif: 'In-App Alerts',
    inAppDesc: 'Toast & sheet popups',
    browserPush: 'Browser Push',
    osNotification: 'Desktop & mobile push',
    emailNotif: 'Email Summaries',
    emailDesc: 'HTML receipts & updates',
    soundEffects: 'Sound Chimes',
    soundDesc: 'Audible alert tone',
    alertCategories: 'Notification Topics & Activities',
    orderUpdates: 'Orders & Deliveries',
    orderUpdatesDesc: 'New orders, dispatch status, acceptance, and cancellations',
    bookingUpdates: 'Craftsmen & Service Bookings',
    bookingUpdatesDesc: 'Appointment reservations, confirmations, and reminders',
    paymentUpdates: 'Payments, Escrow & Refunds',
    paymentUpdatesDesc: 'Deposit confirmations, escrow releases, refunds, and failures',
    withdrawalUpdates: 'Seller & Craftsman Payouts',
    withdrawalUpdatesDesc: 'CCP & bank withdrawal approval and dispatch status',
    messageUpdates: 'Direct Messages & Chat',
    messageUpdatesDesc: 'Messages from customers, sellers, or craftsmen',
    disputesAndReviews: 'Disputes & Reviews',
    disputesAndReviewsDesc: 'Escrow dispute cases, arbitration updates, and reviews',
    verificationUpdates: 'Account & KYC Verification',
    verificationUpdatesDesc: 'Approval or revision requests for provider badge and store',
    adminAnnouncements: 'Khidmatik Platform Announcements',
    announcementsDesc: 'Platform updates, service releases, and policy notices',
    clearRead: 'Clear Read',
    savePreferences: 'Save Preferences',
    allNotifications: 'All Notifications',
    noUnreadNotifications: 'No unread notifications',
    noNotificationsYet: 'No notifications yet',
    notificationsAutoDesc: 'Orders, bookings, payments, and system updates will appear here in real-time.',
    noNotificationsFound: 'No matching notifications found',
    tryDifferentSearch: 'Try adjusting your search terms or clearing active filters.',
    notificationCenterEmptyDesc: 'You are all caught up! New orders, bookings, transactions, and announcements will appear here.',
    clearSearch: 'Clear Search',
    simulateEvent: 'Test Alerts (17 Types)',
    unreadOnly: 'Unread',
    readOnly: 'Read',
    searchNotifications: 'Search notifications...',

    // Real-Time Messaging System
    attachImage: 'Attach Image',
    attachFile: 'Attach File',
    all: 'All',
    online: 'Online',
    offline: 'Offline',
    storeOwner: 'Store Owner',
    serviceProvider: 'Service Provider',
    supportAgent: 'Support Agent',
    customer: 'Customer',
    reportUser: 'Report User',
    blockUser: 'Block User',
    unblockUser: 'Unblock User',
    startConversation: 'Start a Conversation',
    startConversationDesc: 'Send a message or attachment to get in touch directly.',
    replyingTo: 'Replying to',
    noConversationsYet: 'No conversations yet.',
    noMessagesYet: 'No messages yet.',
    openMessagingHub: 'Open Messaging Hub',
    chatBlockedWarning: 'This conversation is blocked. You cannot send or receive messages.',
    viewListing: 'View Listing / Context',
    reportSubmitted: 'Report Submitted',
    reportSubmittedDesc: 'Thank you. Our trust and safety team will review this report within 24 hours.',
    userBlocked: 'User Blocked',
    userBlockedDesc: 'This user will no longer be able to send you messages.',
    userUnblocked: 'User Unblocked',
    userUnblockedDesc: 'You can now exchange messages with this user.',
    selectConversationDesc: 'Choose a chat from the sidebar or start a new message directly from any store, service, or support page.',

    // Upgraded Review & Rating System
    basedOn: 'Based on',
    verifiedReviews: 'verified reviews',
    verifiedPurchases: 'Verified Purchases',
    verifiedPurchase: 'Verified Purchase',
    verifiedReview: 'Verified Customer Review',
    writeAReview: 'Write a Verified Review',
    ratingDistribution: 'Rating Distribution',
    clearStarFilter: 'Show all ratings',
    detailedCriteria: 'Evaluation Criteria',
    criteria_quality: 'Quality of Work / Items',
    criteria_price: 'Price & Value for Money',
    criteria_communication: 'Communication & Response',
    criteria_punctuality: 'Punctuality & Delivery Speed',
    criteria_professionalism: 'Professionalism & Expertise',
    viewCriteriaRatings: 'Detailed Criteria Ratings',
    sellerResponse: 'Provider Response',
    helpful: 'Helpful',
    reply: 'Reply',
    report: 'Report',
    rateAndReview: 'Rate & Review',
    writeReviewDesc: 'Share your genuine experience with detailed multi-criteria feedback.',
    selectOrderToReview: 'Select Completed Order / Service',
    overallRating: 'Overall Rating',
    rateSpecificAspects: 'Detailed Aspect Ratings',
    reviewTitle: 'Review Headline (Optional)',
    reviewTitlePlaceholder: 'e.g. Excellent service and authentic products!',
    detailedReview: 'Detailed Review',
    detailedReviewPlaceholder: 'What did you like or dislike? How was the service, communication, and delivery?',
    addPhotosVideos: 'Add Photos or Video Clips (Optional)',
    uploadMedia: 'Upload Media',
    mediaUploadHint: 'Upload up to 6 high-resolution photos or video demonstrations.',
    publishReview: 'Publish Verified Review',
    officialResponse: 'Official Merchant Response',
    replyToCustomer: 'Reply to',
    replyDesc: 'Your public response will be pinned directly below the customer’s review.',
    yourResponse: 'Your Response',
    replyPlaceholder: 'Thank you for your review! We appreciate your feedback...',
    postResponse: 'Post Official Reply',
    reportThisReview: 'Report Inappropriate Review',
    reportReviewDesc: 'Help us keep Khidmatik authentic. Reports are reviewed by our trust team within 24 hours.',
    selectViolationReason: 'Select Violation Reason',
    additionalDetails: 'Additional Details (Optional)',
    reportDetailsPlaceholder: 'Provide any extra context for our moderation team...',
    submitReport: 'Submit Report',
    verifiedOnly: 'Verified Only',
    withPhotosVideos: 'With Photos & Videos',
    searchReviews: 'Search reviews...',
    mostRecent: 'Most Recent',
    highestRating: 'Highest Rating',
    lowestRating: 'Lowest Rating',
    mostHelpful: 'Most Helpful',
    loadingReviews: 'Loading verified reviews...',
    noReviewsFound: 'No reviews matching your filters',
    beTheFirstReview: 'Have you completed an order or service here? Share your verified feedback with the community.',
    showLess: 'Show less',
    readMore: 'Read more',
  },
  ar: {
    stores: 'المتاجر',
    services: 'الخدمات',
    digital: 'رقمي',
    marketplace: 'السوق',
    profileMenu: 'قائمة الملف الشخصي',
    myAccount: 'حسابي',
    profile: 'الملف الشخصي',
    dashboards: 'لوحات التحكم',
    myStoreDashboard: 'لوحة تحكم متجري',
    servicesAdminPanel: 'لوحة إدارة الخدمات',
    platformSuperAdmin: 'مشرف المنصة العام',
    logOut: 'تسجيل الخروج',
    notifications: 'الإشعارات',
    recentActivityAlertsUpdates: 'الأنشطة الأخيرة، التنبيهات والتحديثات.',
    viewAllNotifications: 'عرض جميع الإشعارات',
    selectLanguage: 'اختر اللغة',
    english: 'English (الإنجليزية)',
    arabic: 'العربية',
    french: 'Français (الفرنسية)',
    logIn: 'تسجيل الدخول',
    register: 'تسجيل',
    welcomeToKhidmatik: 'مرحباً بكم في خدمتك',
    welcomeSubtitle: 'تطبيقك الخارق للجزائر! اكتشف المتاجر، الخدمات، قطع الغيار، والمزيد.',
    browseByCategory: 'تصفح حسب الفئة',
    viewAllListings: 'عرض جميع الفئات والقوائم',
    featuredListings: 'قوائم مميزة',
    madeInAlgeria: 'صنع بفخر في الجزائر',
    exploreAllLocal: 'اكتشف جميع المنتجات المحلية',
    areYouBusinessOwner: 'هل أنت صاحب عمل أو محترف؟',
    joinKhidmatikToday: 'انضم إلى خدمتك اليوم وقم بالوصول إلى المزيد من العملاء في منطقتك.',
    listYourBusiness: 'أدرج عملك أو خدمتك',
    footerRights: 'خدمتك. جميع الحقوق محفوظة.',
    footerSlogan: 'ربط المجتمعات في الجزائر، بنقرة واحدة في كل مرة.',
    appRoadmap: 'خارطة طريق التطبيق',
    servicePoint: 'نقطة الخدمة',
    
    // Marketplace & Parts Mine
    marketplaceTitle: 'مرحباً بكم في السوق المفتوح',
    marketplaceSub: 'مركزك المتخصص لشراء وبيع قطع الغيار الجديدة والمستعملة في الجزائر.',
    partsMineTitle: 'مرحباً بكم في منجم قطع الغيار',
    partsMineSub: 'سوقك المتخصص لشراء وبيع قطع الغيار الجديدة والمستعملة في منطقتك.',
    listPartBtn: 'عرض قطعة غيار للبيع',
    requestPartBtn: 'طلب قطعة غيار مفقودة',
    findSpareParts: 'البحث عن قطع غيار',
    findSparePartsDesc: 'ابحث باسم القطعة، موديل الجهاز، أو استخدم خيارات التصفية أدناه.',
    searchPlaceholderParts: 'ابحث عن اسم القطعة، موديل الجهاز (مثال: شاشة سامسونج، مصباح رينو كليو)...',
    filterCategory: 'تصفية حسب التصنيف...',
    allCategories: 'جميع التصنيفات',
    filterCondition: 'تصفية حسب الحالة...',
    allConditions: 'جميع الحالات',
    filterWilaya: 'تصفية حسب الولاية...',
    allWilayas: 'جميع الولايات',
    searchKeywordPlaceholder: 'الكلمة المفتاحية (مثال: بيتزا، سباك)',
    locationPlaceholder: 'الموقع (مثال: الجزائر الوسطى)',
    searchBtn: 'ابحث',
    advancedFilters: 'تصفية متقدمة',
    capacityLabel: 'الحد الأدنى للسعة',
    capacityPlaceholder: 'السعة (مثال: 100)',
    priceLabel: 'الحد الأقصى للميزانية (د.ج)',
    pricePlaceholder: 'السعر (مثال: 1000)',
    dateLabel: 'التاريخ المفضل',
    selectDate: 'اختر التاريخ',
    myServices: 'خدماتي',
    manageServicesDesc: 'قم بإضافة وتعديل وإدارة الخدمات التي تقدمها للعملاء.',
    addNewServiceBtn: 'إضافة خدمة جديدة',
    serviceListingsTitle: 'قائمة خدماتك المعروضة',
    serviceListingsDesc: 'نظرة عامة على الخدمات التي تقدمها حالياً.',
    searchServicesPlaceholder: 'البحث عن خدمات...',
    filterBtn: 'تصفية',
    filterAll: 'الكل',
    filterActive: 'نشط',
    filterDraft: 'مسودة',
    tableNameHeader: 'اسم الخدمة',
    tableCategoryHeader: 'التصنيف',
    tablePriceHeader: 'السعر الأساسي',
    tableStatusHeader: 'الحالة',
    tableActionsHeader: 'الإجراءات',
    noServicesAdded: 'لم تقم بإضافة أي خدمات بعد.',
    editServiceTitle: 'تعديل الخدمة',
    addNewServiceTitle: 'إضافة خدمة جديدة',
    serviceDetailsDesc: 'قدم معلومات مفصلة عن الخدمة التي تعرضها.',
    formServiceNameLabel: 'اسم الخدمة / العنوان *',
    formServiceDescriptionLabel: 'الوصف التفصيلي *',
    formServiceCategoryLabel: 'تصنيف الخدمة *',
    formBasePriceLabel: 'السعر الأساسي (د.ج)',
    formPriceUnitLabel: 'وحدة التسعير (اختياري)',
    pricingOptionsTitle: 'خيارات التسعير *',
    addCustomPricingBtn: '+ إضافة خيارات تسعير مخصصة',
    deliveryTimeLabel: 'وقت التسليم المقدر / المدة',
    deliveryScheduleTitle: 'التسليم والجدولة',
    setDeliveryScheduleBtn: '+ ضبط خيارات جدول التسليم',
    mediaSectionTitle: 'الوسائط (صور، فيديوهات، ملفات PDF)',
    uploadImagesBtn: 'رفع صور (الحد الأقصى 5)',
    addVideoLinkBtn: 'إضافة رابط فيديو (يوتيوب، فيميو)',
    uploadPdfBtn: 'رفع عينات/كتيبات PDF',
    serviceBundlesTitle: 'حزم / باقات الخدمات',
    serviceBundlesDesc: 'تقديم خدمات مجمعة بسعر خاص.',
    createBundleBtn: 'إنشاء باقة خدمات',
    cancelBtn: 'إلغاء',
    saveServiceBtn: 'حفظ الخدمة',
    toastServiceCreated: 'تم إنشاء الخدمة',
    toastServiceUpdated: 'تم تحديث الخدمة',
    toastServiceSavedDesc: 'تم حفظ تفاصيل الخدمة بنجاح.',
    toastServiceDeleted: 'تم حذف الخدمة',
    toastServiceDeletedDesc: 'تمت إزالة الخدمة بنجاح.',
    recentlyListed: 'قطع الغيار المعروضة حديثاً',
    noPartsFound: 'لا توجد قطع غيار تطابق بحثك أو خيارات التصفية.',
    noPartsFoundSub: 'حاول تعديل كلمات البحث أو تصفح جميع قطع الغيار المتاحة.',
    aiDiscovery: 'الاكتشاف المدعوم بالذكاء الاصطناعي',
    aiDiscoverySub: 'نظام الذكاء الاصطناعي يساعدك في العثور على احتياجاتك بدقة!',
    smartRequestMatching: 'المطابقة الذكية للطلبات',
    smartRequestMatchingDesc: 'عند قيامك بطلب قطعة غيار، يبحث نظامنا الذكي في القوائم ويبلغك فور توفرها أو عند توفر بائع ملائم.',
    enhancedSearch: 'البحث المتقدم والمحسن (قريباً)',
    enhancedSearchDesc: 'سيقترح الذكاء الاصطناعي قطع الغيار المتوافقة أو البدائل المناسبة.',
    exampleAiSuggestion: 'مثال على اقتراح الذكاء الاصطناعي (نموذج):',
    exampleAiText: '"لاحظنا أنك طلبت مؤخراً فني صيانة ثلاجات. قد تكون مهتماً بقطع الغيار هذه لثلاجتك..."',
    activeRequests: 'طلبات قطع الغيار النشطة الخاصة بي',
    secureTransactions: 'المعاملات المالية الآمنة',
    secureTransactionsDesc: 'تتم كافة المعاملات في منصتنا بمراعاة تامة لأمان المستخدم وحفظ حقوقه في الجزائر.',
    inAppComm: 'التواصل داخل التطبيق',
    inAppCommDesc: 'تحدث بأمان وسرية مع البائعين والمشترين للاتفاق على التفاصيل.',
    escrowWallet: 'حماية المشتري عبر محفظة الضمان',
    escrowWalletDesc: 'تحتفظ المنصة بالمبلغ بأمان ولا تسلمه للبائع حتى تؤكد استلامك للقطعة بنفس المواصفات.',
    disputeRes: 'نظام فض النزاعات',
    disputeResDesc: 'يتوفر دعم فني متكامل للمساعدة وحل أي مشكلة أو اختلاف قد يطرأ.',
    advancedFiltersSoon: 'الفلاتر المتقدمة حسب العلامة التجارية ونطاق السعر ستتوفر قريباً.',

    // Digital Services
    digitalServicesTitle: 'الخدمات الرقمية',
    exploreDigitalServices: 'اكتشف الخدمات الرقمية',
    findFreelancersSub: 'اعثر على أفضل المستقلين ومزودي الخدمات الرقمية المحليين في الجزائر.',
    searchFreelancerPlaceholder: 'ابحث باسم المستقل، المهارة، نوع الخدمة...',
    allDigitalCategories: 'جميع فئات الخدمات الرقمية',
    searchDigitalBtn: 'بحث في الخدمات الرقمية',
    noFreelancersFound: 'لم يتم العثور على مستقلين',
    noFreelancersFoundSub: 'لم نجد أي مستقلين يطابقون معايير البحث الحالية. يرجى تعديل البحث أو الفلاتر.',
    clearFiltersBtn: 'إعادة تعيين الفلاتر والبحث مجدداً',

    // Dashboards & Sidebar
    storeDashboard: 'لوحة تحكم المتجر',
    overview: 'لوحة التحكم',
    ordersReturns: 'جميع الطلبات',
    productsInventory: 'المنتجات والمخزون',
    customersReviews: 'العملاء والتقييمات',
    marketingPromotions: 'التسويق والترويج',
    financialsPayouts: 'المالية',
    aiSellerAssistant: 'مساعد البائع الذكي',
    analyticsReports: 'التقارير والتحليلات',
    storeSettingsConfig: 'إعدادات المتجر',
    suppliers: 'الموردين',
    backToMainSite: 'العودة للموقع الرئيسي',
    scheduledOrders: 'الطلبات المبرمجة',
    newOrder: 'طلب جديد',
    failureManagement: 'إدارة الإخفاقات',
    stockInventory: 'المخزون والجرد',
    salesChannels: 'قنوات البيع',
    dispatchOrders: 'توزيع الطلبات',
    payments: 'المدفوعات',
    teamManagement: 'إدارة الفريق',
    deliverySettings: 'إعدادات التوصيل',
    webhooks: 'الويب هوك وأدوات المطور',
    adminDashboard: 'المشرف العام',
    verificationQueue: 'طلبات التحقق',
    userManagement: 'إدارة المستخدمين',
    storeManagement: 'لوحة تحكم المتجر',
    reservationManagement: 'إدارة الحجوزات',
    providerManagement: 'لوحة إدارة الخدمات',
    financialManagement: 'المدفوعات والاشتراكات',
    platformAnalytics: 'التقارير والإحصائيات',
    contentModeration: 'إدارة المحتوى',
    cmsSiteContent: 'القوالب وإدارة المحتوى',
    systemConfiguration: 'الإعدادات العامة',
    securityAudit: 'السجلات والنسخ الاحتياطي والصيانة',
    aiAdvancedTools: 'الإضافات وواجهات البرمجة',
    supportSystem: 'الدعم والتذاكر',
    myProfile: 'الملف الشخصي',
    actions: 'الإجراءات',
    settings: 'الإعدادات',
    security: 'الأمان',
    accountSettings: 'إعدادات الحساب',
    notificationCenter: 'مركز الإشعارات',
    securityPassword: 'الأمان وكلمة المرور',
    language: 'اللغة',
    appearance: 'المظهر',
    sessionsDevices: 'الجلسات والأجهزة',
    activityLog: 'سجل النشاط',
    favorites: 'المفضلة',
    savedItems: 'العناصر المحفوظة',
    myFiles: 'ملفاتي',
    messages: 'الرسائل',
    lastLogin: 'آخر تسجيل دخول',
    accountStatus: 'حالة الحساب',
    subscriptionType: 'نوع الاشتراك',
    accountCreated: 'تاريخ إنشاء الحساب',
    phone: 'رقم الهاتف',
    emailVerified: 'التحقق من البريد الإلكتروني',
    phoneVerified: 'التحقق من الهاتف',
    markAllRead: 'تحديد الكل كمقروء',
    notificationPref: 'تفضيلات الإشعارات',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    pushNotifications: 'الإشعارات الفورية',
    changePassword: 'تغيير كلمة المرور',
    twoFactorAuth: 'التحقق بخطوتين (2FA)',
    loginHistory: 'سجل الدخول',
    activeSessions: 'الجلسات النشطة',
    trustedDevices: 'الأجهزة الموثوقة',
    apiTokens: 'واجهات API للربط',
    theme: 'المظهر (الثيم)',
    fontSize: 'حجم الخط',
    changeAvatar: 'تغيير الصورة الشخصية',
    quickStats: 'إحصائيات سريعة',
    ordersToday: 'طلبات اليوم',
    storesCount: 'المتاجر',
    servicesCount: 'الخدمات',
    pendingTickets: 'تذاكر معلقة',
    revenueToday: 'أرباح اليوم',
    newUsers: 'مستخدمين جدد',
    logoutAllDevices: 'تسجيل الخروج من كل الأجهزة',
    logoutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
    logoutConfirmDesc: 'سيتم إنهاء الجلسة الحالية الخاصة بك.',
    logoutCurrent: 'تسجيل الخروج من الجلسة الحالية',
    active: 'نشط',
    yes: 'نعم',
    no: 'لا',
    verified: 'موثق',

    // Professional Dashboard Additions
    publicProfile: 'الملف الشخصي العام',
    verificationBadges: 'التحقق والشارات',
    serviceManagement: 'إدارة الخدمات',
    bookingsCalendar: 'الحجوزات والتقويم',
    projectsOrders: 'المشاريع والطلبات',
    earningsPayouts: 'الأرباح والمدفوعات',
    clientCommunication: 'التواصل مع العملاء',
    performanceAnalytics: 'تحليلات الأداء',
    settingsIntegrations: 'الإعدادات والتكامل',
    helpSupport: 'المساعدة والدعم',
    servicesAdmin: 'إدارة الخدمات',

    // Dashboard Sections - Bookings
    manageAppointments: 'إدارة المواعيد والتوفر وحجوزات العملاء.',
    addAppointment: 'إضافة موعد',
    myCalendar: 'تقويمي',
    manageAvailability: 'إدارة التوفر',
    appointmentsFor: 'المواعيد ليوم',
    today: 'اليوم',
    reviewAppointments: 'مراجعة وإدارة المواعيد المجدولة لليوم المحدد.',
    time: 'الوقت',
    client: 'العميل',
    service: 'الخدمة',
    confirmed: 'مؤكد',
    cancelled: 'ملغي',
    pending: 'قيد الانتظار',
    noAppointments: 'لا توجد مواعيد مجدولة لهذا اليوم.',
    scheduleNewAppointment: 'جدولة موعد جديد مع عميل.',
    clientName: 'اسم العميل',
    notes: 'ملاحظات',
    optionalNotes: 'ملاحظات اختيارية...',
    appointmentDetails: 'تفاصيل الموعد',
    appointmentAdded: 'تمت إضافة الموعد',
    appointmentAddedDesc: 'تم جدولة موعد جديد.',
    appointmentConfirmed: 'تم تأكيد الموعد',
    appointmentCancelled: 'تم إلغاء الموعد',
    setWorkingHours: 'تحديد ساعات العمل والفاصل الزمني بين المواعيد.',
    startHour: 'ساعة البدء',
    endHour: 'ساعة الانتهاء',
    bufferTime: 'الفاصل الزمني (بالدقائق)',
    availabilitySaved: 'تم حفظ التوفر',
    availabilitySavedDesc: 'تم تحديث ساعات العمل.',
    close: 'إغلاق',

    // Dashboard Sections - Projects
    trackProjects: 'تتبع الخدمات الجارية ومشاريع العملاء وحالات الطلبات.',
    currentProjects: 'المشاريع/الطلبات الحالية',
    manageProgress: 'إدارة تقدم وحالة تعاملاتك مع العملاء.',
    searchProjects: 'البحث بالعميل أو اسم الخدمة...',
    filterByStatus: 'تصفية حسب الحالة',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    scheduled: 'مجدول',
    awaitingFeedback: 'بانتظار العميل',
    rejected: 'مرفوض',
    projectId: 'رقم المشروع',
    deadline: 'الموعد النهائي',
    payment: 'الدفع',
    noProjects: 'لا توجد مشاريع أو طلبات نشطة.',
    quickActions: 'إجراءات سريعة',
    markCompleted: 'تحديد كمكتمل',
    requestRevision: 'طلب مراجعة',
    cancelOrder: 'إلغاء الطلب',
    sendUpdate: 'إرسال تحديث',
    projectDetails: 'تفاصيل المشروع',
    statusUpdated: 'تم تحديث الحالة',
    projectStatus: 'تم تغيير حالة المشروع إلى',
    sendUpdateToClient: 'إرسال تحديث للعميل',
    typeUpdate: 'اكتب رسالة التحديث...',
    updateSent: 'تم إرسال التحديث',
    updateSentTo: 'تم إرسال التحديث للعميل للمشروع',

    // Dashboard Sections - Communication
    manageCommunication: 'إدارة الرسائل وتتبع المحادثات والبقاء على تواصل مع عملائك.',
    myConversations: 'محادثاتي',
    searchMessages: 'بحث...',
    selectConversation: 'اختر محادثة لبدء المراسلة.',
    realtimeMessaging: 'مراسلة فورية مع عميلك.',
    typeMessage: 'اكتب رسالتك...',
    messageSent: 'تم إرسال الرسالة',
    conversationArchived: 'تم تحديث المحادثة',
    noConversations: 'لا توجد محادثات.',

    // Dashboard Sections - Marketing
    boostVisibility: 'عزز ظهورك واجذب المزيد من العملاء بأدوات ترويجية.',
    discountCoupons: 'كوبونات الخصم والرموز الترويجية',
    createManageCoupons: 'إنشاء وإدارة رموز الخصم لخدماتك.',
    couponCode: 'رمز الكوبون',
    discountType: 'نوع الخصم',
    percentage: 'نسبة مئوية (%)',
    fixedAmount: 'مبلغ ثابت (د.ج)',
    valueAmount: 'القيمة / المبلغ',
    expiryDate: 'تاريخ الانتهاء (اختياري)',
    usageLimit: 'حد الاستخدام (0 = غير محدود)',
    createCoupon: 'إنشاء كوبون',
    existingCoupons: 'الكوبونات الموجودة',
    code: 'الرمز',
    discount: 'الخصم',
    usage: 'الاستخدام',
    expired: 'منتهي',
    couponCreated: 'تم إنشاء الكوبون',
    couponDeleted: 'تم حذف الكوبون',
    clientTargeting: 'استهداف العملاء',
    clientTargetingDesc: 'أدوات لتشغيل عروض ترويجية مستهدفة لفئات محددة من العملاء.',

    // Dashboard Sections - Earnings
    trackEarnings: 'تتبع أرباحك وإدارة الفواتير وطلب السحب.',
    totalEarned: 'إجمالي الأرباح',
    pendingPayout: 'السحب المعلق',
    platformFees: 'رسوم المنصة',
    netEarnings: 'صافي الأرباح',
    transactionHistory: 'سجل المعاملات والفواتير',
    viewPayments: 'عرض جميع المدفوعات والعمولات وإنشاء الفواتير.',
    description: 'الوصف',
    type: 'النوع',
    amount: 'المبلغ (د.ج)',
    invoice: 'الفاتورة',
    exportData: 'تصدير بيانات الأرباح',
    withdrawalSystem: 'نظام السحب',
    requestPayouts: 'طلب سحب الأرباح إلى حسابك البنكي أو وسائل أخرى.',
    currentMethod: 'طريقة الدفع الحالية',
    requestWithdrawal: 'طلب سحب جديد',
    managePayoutMethods: 'إدارة طرق الدفع',
    commissionNote: 'يتم احتساب عمولات المنصة تلقائياً وخصمها قبل السحب. مدة معالجة السحب القياسية هي 3-5 أيام عمل.',
    enterWithdrawAmount: 'أدخل المبلغ الذي ترغب في سحبه.',
    payoutMethod: 'طريقة الدفع',
    selectMethod: 'اختر الطريقة...',
    submitWithdrawal: 'تأكيد السحب',
    withdrawalRequested: 'تم طلب السحب',
    willBeProcessed: 'ستتم معالجته خلال 3-5 أيام عمل.',
    addNewMethod: 'إضافة طريقة جديدة',
    accountDetails: 'تفاصيل الحساب (مثال: رقم الحساب)',
    addMethod: 'إضافة طريقة',
    payoutMethodAdded: 'تمت إضافة طريقة الدفع',
    exportComplete: 'اكتمل التصدير',
    csvDownloaded: 'تم تحميل ملف CSV.',
    invoiceGenerated: 'تم إنشاء الفاتورة',
    downloaded: 'تم التحميل',

    // Dashboard Sections - Support
    getHelp: 'احصل على المساعدة وجد الإجابات وأدر طلبات الدعم الخاصة بك.',
    submitRequest: 'تقديم طلب دعم جديد',
    needHelp: 'هل تحتاج مساعدة مع المنصة أو لديك مشكلة؟ أخبرنا.',
    subject: 'الموضوع',
    category: 'التصنيف',
    selectCategory: 'اختر تصنيف المشكلة...',
    technicalIssue: 'مشكلة تقنية',
    billingPayment: 'الفواتير/الدفع',
    serviceListing: 'قائمة الخدمات',
    accountHelp: 'مساعدة الحساب',
    other: 'أخرى',
    describeIssue: 'وصف المشكلة',
    provideDetails: 'يرجى تقديم أكبر قدر ممكن من التفاصيل...',
    submitTicket: 'إرسال التذكرة',
    myTickets: 'تذاكر الدعم الخاصة بي',
    trackTickets: 'تتبع حالة طلبات الدعم المقدمة.',
    searchTickets: 'البحث في تذاكري...',
    ticketId: 'رقم التذكرة',
    lastUpdate: 'آخر تحديث',
    open: 'مفتوح',
    resolved: 'تم الحل',
    viewReply: 'عرض/الرد',
    noTickets: 'لا توجد تذاكر دعم.',
    knowledgeBase: 'قاعدة المعرفة والأسئلة الشائعة',
    findAnswers: 'ابحث عن إجابات للأسئلة الشائعة وتعلم كيفية استخدام المنصة.',
    ticketSubmitted: 'تم إرسال التذكرة',
    ticketSubmittedDesc: 'تم إرسال طلب الدعم الخاص بك.',
    originalMessage: 'الرسالة الأصلية',
    you: 'أنت',
    supportTeam: 'فريق الدعم',
    yourReply: 'ردك',
    typeReply: 'اكتب ردك...',
    sendReply: 'إرسال الرد',
    replySent: 'تم إرسال الرد',
    justNow: 'الآن',
    ago: 'مضت',

    // Reservations
    reservationsTitle: 'الحجوزات',
    banquetHallsReservations: 'حجوزات قاعات الحفلات',

    // AI Refinements
    aiRefinementsTitle: 'هل تحتاج مساعدة في تخصيص بحثك؟',
    getAiSuggestions: 'احصل على اقتراحات الذكاء الاصطناعي',
    generatingSuggestions: 'جاري توليد الاقتراحات...',
    aiRefinementsClickDesc: "انقر على 'احصل على اقتراحات الذكاء الاصطناعي' لمساعدتك في تضييق نطاق نتائج البحث.",
    noRefinementsFound: 'لم يتم العثور على اقتراحات محددة للبحث الحالي.',
    errRefinements: 'فشل جلب اقتراحات البحث بالذكاء الاصطناعي. يرجى المحاولة لاحقاً.',

    // Centralized Notifications
    notificationCenterSub: 'إدارة التنبيهات المباشرة، تحديثات الطلبات، الحجوزات، المدفوعات وإعلانات النظام.',
    notificationPrefSub: 'تخصيص قنوات الاستلام وأنواع التنبيهات التي ترغب في تلقيها.',
    deliveryChannels: 'قنوات الإشعار',
    inAppNotif: 'إشعارات داخل التطبيق',
    inAppDesc: 'نوافذ منبثقة وقائمة سريعة',
    browserPush: 'إشعارات المتصفح الفورية (Push)',
    osNotification: 'إشعارات على سطح المكتب والهاتف',
    emailNotif: 'ملخصات البريد الإلكتروني',
    emailDesc: 'فواتير وتحديثات منسقة عبر الإيميل',
    soundEffects: 'التنبيهات الصوتية',
    soundDesc: 'نغمة صوتية عند استلام إشعار جديد',
    alertCategories: 'مجالات وأنشطة الإشعارات',
    orderUpdates: 'الطلبات والتوصيل',
    orderUpdatesDesc: 'طلبات جديدة، حالة الشحن، القبول والإلغاء',
    bookingUpdates: 'حجوزات الخدمات والحرفيين',
    bookingUpdatesDesc: 'حجز المواعيد، التأكيدات والتذكيرات',
    paymentUpdates: 'المدفوعات، الضمان المالي والاسترجاع',
    paymentUpdatesDesc: 'تأكيد الإيداع، تحرير أموال الضمان، الاسترجاع وفشل الدفع',
    withdrawalUpdates: 'سحوبات البائعين والحرفيين',
    withdrawalUpdatesDesc: 'الموافقة على تحويلات CCP والبنك وحالة الإرسال',
    messageUpdates: 'الرسائل والمحادثات المباشرة',
    messageUpdatesDesc: 'رسائل الزبائن، المتاجر والحرفيين',
    disputesAndReviews: 'النزاعات والتقييمات',
    disputesAndReviewsDesc: 'قضايا الضمان المالي، التحكيم والتقييمات',
    verificationUpdates: 'توثيق الحساب والهوية',
    verificationUpdatesDesc: 'الموافقة على شارة التوثيق أو طلب مستندات إضافية',
    adminAnnouncements: 'إعلانات منصة خدمتك الرسمية',
    announcementsDesc: 'تحديثات المنصة، الخدمات الجديدة والشروط',
    clearRead: 'مسح المقروء',
    savePreferences: 'حفظ التفضيلات',
    allNotifications: 'جميع الإشعارات',
    noUnreadNotifications: 'لا توجد إشعارات غير مقروءة',
    noNotificationsYet: 'لا توجد إشعارات بعد',
    notificationsAutoDesc: 'ستظهر هنا تحديثات الطلبات والحجوزات والمدفوعات مباشرة في الوقت الفعلي.',
    noNotificationsFound: 'لم يتم العثور على إشعارات مطابقة',
    tryDifferentSearch: 'جرب تعديل كلمات البحث أو مسح الفلاتر المحددة.',
    notificationCenterEmptyDesc: 'أنت على اطلاع بكل جديد! ستظهر الطلبات والحجوزات والإعلانات هنا فور حدوثها.',
    clearSearch: 'مسح البحث',
    simulateEvent: 'تجربة التنبيهات (17 نوعاً)',
    unreadOnly: 'غير مقروء',
    readOnly: 'مقروء',
    searchNotifications: 'بحث في الإشعارات...',

    // Real-Time Messaging System
    attachImage: 'إرفاق صورة',
    attachFile: 'إرفاق ملف',
    all: 'الكل',
    online: 'متصل الآن',
    offline: 'غير متصل',
    storeOwner: 'صاحب متجر',
    serviceProvider: 'مزود خدمة',
    supportAgent: 'فريق الدعم',
    customer: 'عميل',
    reportUser: 'إبلاغ عن مستخدم',
    blockUser: 'حظر المستخدم',
    unblockUser: 'إلغاء حظر المستخدم',
    startConversation: 'بدء محادثة',
    startConversationDesc: 'أرسل رسالة أو مرفقاً للتواصل المباشر مع التاجر أو الحرفي أو الدعم.',
    replyingTo: 'الرد على',
    noConversationsYet: 'لا توجد محادثات بعد.',
    noMessagesYet: 'لا توجد رسائل بعد.',
    openMessagingHub: 'فتح مركز الرسائل الكامل',
    chatBlockedWarning: 'هذه المحادثة محظورة. لا يمكنك إرسال أو استقبال الرسائل.',
    viewListing: 'عرض الإعلان / السياق',
    reportSubmitted: 'تم تقديم البلاغ بنجاح',
    reportSubmittedDesc: 'شكراً لك. سيقوم فريق الأمان والنزاهة بمراجعة البلاغ خلال 24 ساعة.',
    userBlocked: 'تم حظر المستخدم',
    userBlockedDesc: 'لن يتمكن هذا المستخدم من إرسال رسائل إليك بعد الآن.',
    userUnblocked: 'تم إلغاء الحظر',
    userUnblockedDesc: 'يمكنك الآن تبادل الرسائل مع هذا المستخدم.',
    selectConversationDesc: 'اختر محادثة من القائمة أو ابدأ محادثة جديدة مباشرة من صفحة أي متجر أو خدمة.',

    // Upgraded Review & Rating System
    basedOn: 'بناءً على',
    verifiedReviews: 'تقييمات موثقة',
    verifiedPurchases: 'طلبات وخدمات موثقة',
    verifiedPurchase: 'طلب موثق',
    verifiedReview: 'تقييم عميل موثق',
    writeAReview: 'كتابة تقييم موثق',
    ratingDistribution: 'توزيع التقييمات',
    clearStarFilter: 'عرض جميع التقييمات',
    detailedCriteria: 'معايير التقييم التفصيلية',
    criteria_quality: 'جودة العمل والمنتجات',
    criteria_price: 'السعر والقيمة مقابل المال',
    criteria_communication: 'التواصل والاستجابة',
    criteria_punctuality: 'الالتزام بالمواعيد والسرعة',
    criteria_professionalism: 'الاحترافية وحسن التعامل',
    viewCriteriaRatings: 'عرض التقييمات التفصيلية للمعايير',
    sellerResponse: 'رد التاجر / المزود',
    helpful: 'مفيد',
    reply: 'رد',
    report: 'إبلاغ',
    rateAndReview: 'التقييم والمراجعة لـ',
    writeReviewDesc: 'شارك تجربتك الموثقة وساعد المجتمع بتقييم دقيق ومتعدد المعايير.',
    selectOrderToReview: 'اختر الطلب أو الخدمة المكتملة للتقييم',
    overallRating: 'التقييم الإجمالي العام',
    rateSpecificAspects: 'تقييم المعايير التفصيلية',
    reviewTitle: 'عنوان المراجعة (اختياري)',
    reviewTitlePlaceholder: 'مثال: خدمة ممتازة وتوصيل سريع وجودة رائعة!',
    detailedReview: 'نص التقييم والملاحظات',
    detailedReviewPlaceholder: 'ما الذي أعجبك أو لم يعجبك؟ كيف كانت الجودة والتعامل والالتزام؟',
    addPhotosVideos: 'إرفاق صور أو مقاطع فيديو توضيحية (اختياري)',
    uploadMedia: 'رفع وسائط',
    mediaUploadHint: 'يمكنك إرفاق حتى 6 صور أو مقاطع فيديو عالية الوضوح.',
    publishReview: 'نشر التقييم الموثق',
    officialResponse: 'الرد الرسمي للتاجر أو المزود',
    replyToCustomer: 'الرد على العميل',
    replyDesc: 'سيتم تثبيت ردك العام مباشرة أسفل تقييم العميل على الصفحة.',
    yourResponse: 'نص ردك الرسمي',
    replyPlaceholder: 'شكراً لتقييمك وكلماتك الطيبة! يسعدنا دائماً خدمتك...',
    postResponse: 'نشر الرد الرسمي',
    reportThisReview: 'إبلاغ عن تقييم مخالف أو غير لائق',
    reportReviewDesc: 'ساعدنا في الحفاظ على مصداقية المنصة. تتم مراجعة البلاغات من قبل فريق النزاهة خلال 24 ساعة.',
    selectViolationReason: 'اختر سبب المخالفة',
    additionalDetails: 'تفاصيل إضافية (اختياري)',
    reportDetailsPlaceholder: 'قدم أي توضيحات إضافية لمساعدة فريق الإشراف...',
    submitReport: 'إرسال البلاغ',
    verifiedOnly: 'الموثقة فقط',
    withPhotosVideos: 'مع صور وفيديو',
    searchReviews: 'البحث في المراجعات...',
    mostRecent: 'الأحدث',
    highestRating: 'الأعلى تقييماً',
    lowestRating: 'الأقل تقييماً',
    mostHelpful: 'الأكثر إفادة',
    loadingReviews: 'جاري تحميل التقييمات الموثقة...',
    noReviewsFound: 'لا توجد تقييمات مطابقة لخيارات البحث',
    beTheFirstReview: 'هل أكملت طلباً أو خدمة هنا؟ كن أول من يشارك تقييماً موثقاً لمساعدة المجتمع.',
    showLess: 'عرض أقل',
    readMore: 'قراءة المزيد',
  },
  fr: {
    stores: 'Magasins',
    services: 'Services',
    digital: 'Numérique',
    marketplace: 'Marketplace',
    profileMenu: 'Menu Profil',
    myAccount: 'Mon Compte',
    profile: 'Profil',
    dashboards: 'Tableaux de Bord',
    myStoreDashboard: 'Tableau de Bord Magasin',
    servicesAdminPanel: 'Admin Services',
    platformSuperAdmin: 'Super Admin Plateforme',
    logOut: 'Déconnexion',
    notifications: 'Notifications',
    recentActivityAlertsUpdates: 'Activité récente, alertes et mises à jour.',
    viewAllNotifications: 'Voir toutes les notifications',
    selectLanguage: 'Choisir la langue',
    english: 'English (Anglais)',
    arabic: 'العربية (Arabe)',
    french: 'Français',
    logIn: 'Se Connecter',
    register: 'S\'inscrire',
    welcomeToKhidmatik: 'Bienvenue à Khidmatik',
    welcomeSubtitle: 'Votre Super-App pour l\'Algérie ! Découvrez magasins, services, pièces détachées, et plus encore.',
    browseByCategory: 'Parcourir par catégorie',
    viewAllListings: 'Voir toutes les catégories et annonces',
    featuredListings: 'Annonces en Vedette',
    madeInAlgeria: 'Fièrement Fabriqué en Algérie',
    exploreAllLocal: 'Explorer Tous les Produits Locaux',
    areYouBusinessOwner: 'Êtes-vous Propriétaire d\'Entreprise ou Professionnel ?',
    joinKhidmatikToday: 'Rejoignez Khidmatik aujourd\'hui et atteignez plus de clients dans votre région.',
    listYourBusiness: 'Inscrire Votre Entreprise ou Service',
    footerRights: 'Khidmatik. Tous droits réservés.',
    footerSlogan: 'Connecter les communautés en Algérie, un clic à la fois.',
    appRoadmap: 'Feuille de Route',
    servicePoint: 'Point de Service',
    
    // Marketplace & Parts Mine
    marketplaceTitle: 'Bienvenue sur le Marketplace',
    marketplaceSub: 'Votre hub spécialisé pour l\'achat et la vente de pièces détachées neuves & d\'occasion en Algérie.',
    partsMineTitle: 'Bienvenue dans la Mine de Pièces',
    partsMineSub: 'Votre marché spécialisé pour l\'achat et la vente de pièces détachées neuves & d\'occasion.',
    listPartBtn: 'Publier une Pièce à Vendre',
    requestPartBtn: 'Demander une Pièce Manquante',
    findSpareParts: 'Trouver des Pièces Détachées',
    findSparePartsDesc: 'Recherchez par nom de pièce, modèle d\'appareil ou utilisez les filtres ci-dessous.',
    searchPlaceholderParts: 'Rechercher une pièce, modèle d\'appareil (ex: écran Samsung S10, phare Clio IV)...',
    filterCategory: 'Filtrer par Catégorie...',
    allCategories: 'Toutes les Catégories',
    filterCondition: 'Filtrer par État...',
    allConditions: 'Tous les États',
    filterWilaya: 'Filtrer par Wilaya...',
    allWilayas: 'Toutes les Wilayas',
    searchKeywordPlaceholder: 'Mot-clé (ex: pizza, plombier)',
    locationPlaceholder: 'Emplacement (ex: Alger Centre)',
    searchBtn: 'Rechercher',
    advancedFilters: 'Filtres Avancés',
    capacityLabel: 'Capacité Minimale',
    capacityPlaceholder: 'Capacité (ex: 100)',
    priceLabel: 'Budget Maximum (DA)',
    pricePlaceholder: 'Prix (ex: 1000)',
    dateLabel: 'Date Souhaitée',
    selectDate: 'Choisir la Date',
    myServices: 'Mes Services',
    manageServicesDesc: 'Ajoutez, modifiez et gérez les services que vous proposez aux clients.',
    addNewServiceBtn: 'Ajouter un Nouveau Service',
    serviceListingsTitle: 'Vos Offres de Services',
    serviceListingsDesc: 'Aperçu des services que vous proposez actuellement.',
    searchServicesPlaceholder: 'Rechercher des services...',
    filterBtn: 'Filtrer',
    filterAll: 'Tous',
    filterActive: 'Actif',
    filterDraft: 'Brouillon',
    tableNameHeader: 'Nom du Service',
    tableCategoryHeader: 'Catégorie',
    tablePriceHeader: 'Prix de Base',
    tableStatusHeader: 'Statut',
    tableActionsHeader: 'Actions',
    noServicesAdded: "Vous n'avez pas encore ajouté de services.",
    editServiceTitle: 'Modifier le Service',
    addNewServiceTitle: 'Ajouter un Nouveau Service',
    serviceDetailsDesc: 'Fournissez des informations détaillées sur le service que vous proposez.',
    formServiceNameLabel: 'Nom du Service / Titre *',
    formServiceDescriptionLabel: 'Description Détaillée *',
    formServiceCategoryLabel: 'Catégorie de Service *',
    formBasePriceLabel: 'Prix de Base (DA)',
    formPriceUnitLabel: 'Unité de Prix (Optionnel)',
    pricingOptionsTitle: 'Options de Tarification *',
    addCustomPricingBtn: '+ Ajouter des options de tarification personnalisées',
    deliveryTimeLabel: 'Délai de Livraison Estimé / Durée',
    deliveryScheduleTitle: 'Livraison & Calendrier',
    setDeliveryScheduleBtn: '+ Configurer le calendrier de livraison',
    mediaSectionTitle: 'Médias (Images, Vidéos, PDFs)',
    uploadImagesBtn: 'Téléverser des images (max 5)',
    addVideoLinkBtn: 'Ajouter un lien vidéo (YouTube, Vimeo)',
    uploadPdfBtn: 'Téléverser des échantillons/brochures PDF',
    serviceBundlesTitle: 'Packs / Forfaits de Services',
    serviceBundlesDesc: 'Proposez des services combinés à un prix spécial.',
    createBundleBtn: 'Créer un Pack de Services',
    cancelBtn: 'Annuler',
    saveServiceBtn: 'Enregistrer le Service',
    toastServiceCreated: 'Service Créé',
    toastServiceUpdated: 'Service Modifié',
    toastServiceSavedDesc: 'Détails du service enregistrés avec succès.',
    toastServiceDeleted: 'Service Supprimé',
    toastServiceDeletedDesc: 'Le service a été supprimé.',
    recentlyListed: 'Pièces Récemment Publiées',
    noPartsFound: 'Aucune pièce ne correspond à votre recherche ou à vos filtres.',
    noPartsFoundSub: 'Essayez d\'ajuster votre recherche ou de voir toutes les pièces disponibles.',
    aiDiscovery: 'Découverte par IA',
    aiDiscoverySub: 'Notre intelligence artificielle vous aide à trouver ce dont vous avez besoin !',
    smartRequestMatching: 'Correspondance Intelligente',
    smartRequestMatchingDesc: 'Lorsque vous demandez une pièce, notre IA recherche les annonces et vous informe des correspondances. Les vendeurs peuvent aussi être notifiés.',
    enhancedSearch: 'Recherche Améliorée (Bientôt)',
    enhancedSearchDesc: 'L\'IA vous suggérera des pièces compatibles ou des alternatives.',
    exampleAiSuggestion: 'Exemple de Suggestion d\'IA (Conceptuel) :',
    exampleAiText: '"Nous avons remarqué que vous avez récemment demandé un dépanneur de frigo. Ces pièces pourraient vous intéresser..."',
    activeRequests: 'Mes Demandes de Pièces Actives',
    secureTransactions: 'Transactions Sécurisées',
    secureTransactionsDesc: 'Toutes les transactions au sein du Marketplace/Mine de pièces sont conçues avec votre sécurité à l\'esprit.',
    inAppComm: 'Communication Intégrée',
    inAppCommDesc: 'Discutez en toute sécurité avec les vendeurs/acheteurs pour convenir de la livraison.',
    escrowWallet: 'Protection par Portefeuille Escrow',
    escrowWalletDesc: 'Les paiements sont bloqués de manière sécurisée jusqu\'à confirmation de la réception de l\'article.',
    disputeRes: 'Résolution des Litiges',
    disputeResDesc: 'Un mécanisme d\'assistance sera disponible en cas de désaccord pour vous aider.',
    advancedFiltersSoon: 'Les filtres avancés par marque et par prix seront bientôt disponibles.',

    // Digital Services
    digitalServicesTitle: 'Services Numériques',
    exploreDigitalServices: 'Explorer les Services Numériques',
    findFreelancersSub: 'Trouvez des freelances et des prestataires de services numériques locaux en Algérie.',
    searchFreelancerPlaceholder: 'Rechercher par nom, compétence, service...',
    allDigitalCategories: 'Toutes les Catégories Numériques',
    searchDigitalBtn: 'Rechercher des Services Numériques',
    noFreelancersFound: 'Aucun Prestataire Trouvé',
    noFreelancersFoundSub: "Nous n'avons trouvé aucun freelance correspondant à vos critères. Essayez d'ajuster votre recherche.",
    clearFiltersBtn: 'Effacer les Filtres et Réessayer',

    // Dashboards & Sidebar
    storeDashboard: 'Tableau de Bord Magasin',
    overview: 'Tableau de bord',
    ordersReturns: 'Toutes les commandes',
    productsInventory: 'Produits & Inventaire',
    customersReviews: 'Clients & Évaluations',
    marketingPromotions: 'Marketing & Promotions',
    financialsPayouts: 'Finances',
    aiSellerAssistant: 'Assistant Vendeur IA',
    analyticsReports: 'Analyses & Rapports',
    storeSettingsConfig: 'Configuration Magasin',
    suppliers: 'Fournisseurs',
    backToMainSite: 'Retour au Site Principal',
    scheduledOrders: 'Commandes programmées',
    newOrder: 'Nouvelle commande',
    failureManagement: 'Gestion des échecs',
    stockInventory: 'Stock & Inventaire',
    salesChannels: 'Canaux de vente',
    dispatchOrders: 'Dispatch Commandes',
    payments: 'Paiements',
    teamManagement: 'Équipe',
    deliverySettings: 'Paramètres livraison',
    webhooks: 'Webhooks',
    adminDashboard: 'Super Admin',
    verificationQueue: 'File de vérification',
    userManagement: 'Gestion des utilisateurs',
    storeManagement: 'Gestion des magasins',
    reservationManagement: 'Gestion des réservations',
    providerManagement: 'Panneau admin des services',
    financialManagement: 'Paiements & Abonnements',
    platformAnalytics: 'Rapports & Statistiques',
    contentModeration: 'Modération de contenu',
    cmsSiteContent: 'Modèles & CMS',
    systemConfiguration: 'Paramètres généraux',
    securityAudit: 'Logs, Sauvegardes & Maintenance',
    aiAdvancedTools: 'Plugins & APIs',
    supportSystem: 'Support & Tickets',
    myProfile: 'Mon Profil',
    actions: 'Actions',
    settings: 'Paramètres',
    security: 'Sécurité',
    accountSettings: 'Paramètres du Compte',
    notificationCenter: 'Centre de Notifications',
    securityPassword: 'Sécurité & Mot de Passe',
    language: 'Langue',
    appearance: 'Apparence',
    sessionsDevices: 'Sessions & Appareils',
    activityLog: 'Journal d\'Activité',
    favorites: 'Favoris',
    savedItems: 'Articles Enregistrés',
    myFiles: 'Mes Fichiers',
    messages: 'Messages',
    lastLogin: 'Dernière Connexion',
    accountStatus: 'Statut du Compte',
    subscriptionType: 'Type d\'Abonnement',
    accountCreated: 'Créé le',
    phone: 'Téléphone',
    emailVerified: 'Email Vérifié',
    phoneVerified: 'Téléphone Vérifié',
    markAllRead: 'Tout marquer comme lu',
    notificationPref: 'Préférences de Notifications',
    emailNotifications: 'Notifications par Email',
    pushNotifications: 'Notifications Push',
    changePassword: 'Modifier le mot de passe',
    twoFactorAuth: 'Authentification à deux facteurs (2FA)',
    loginHistory: 'Historique des connexions',
    activeSessions: 'Sessions Actives',
    trustedDevices: 'Appareils de Confiance',
    apiTokens: 'Jetons API',
    theme: 'Thème',
    fontSize: 'Taille de la police',
    changeAvatar: 'Modifier la photo',
    quickStats: 'Statistiques Rapides',
    ordersToday: 'Commandes aujourd\'hui',
    storesCount: 'Magasins',
    servicesCount: 'Services',
    pendingTickets: 'Tickets en attente',
    revenueToday: 'Revenu aujourd\'hui',
    newUsers: 'Nouveaux utilisateurs',
    logoutAllDevices: 'Se déconnecter de tous les appareils',
    logoutConfirm: 'Êtes-vous sûr de vouloir vous déconnecter?',
    logoutConfirmDesc: 'Vous serez déconnecté de votre session actuelle.',
    logoutCurrent: 'Se déconnecter',
    active: 'Actif',
    yes: 'Oui',
    no: 'Non',
    verified: 'Vérifié',

    // Professional Dashboard Additions
    publicProfile: 'Profil Public',
    verificationBadges: 'Vérification & Badges',
    serviceManagement: 'Gestion des Services',
    bookingsCalendar: 'Réservations & Calendrier',
    projectsOrders: 'Projets & Commandes',
    earningsPayouts: 'Gains & Versements',
    clientCommunication: 'Communication Clients',
    performanceAnalytics: 'Analyses de Performance',
    settingsIntegrations: 'Paramètres & Intégrations',
    helpSupport: 'Aide & Support',
    servicesAdmin: 'Admin Services',

    // Dashboard Sections - Bookings
    manageAppointments: 'Gérez vos rendez-vous, disponibilités et réservations clients.',
    addAppointment: 'Ajouter un Rendez-vous',
    myCalendar: 'Mon Calendrier',
    manageAvailability: 'Gérer la Disponibilité',
    appointmentsFor: 'Rendez-vous pour le',
    today: "Aujourd'hui",
    reviewAppointments: 'Consultez et gérez vos rendez-vous programmés pour la date sélectionnée.',
    time: 'Heure',
    client: 'Client',
    service: 'Service',
    confirmed: 'Confirmé',
    cancelled: 'Annulé',
    pending: 'En Attente',
    noAppointments: 'Aucun rendez-vous programmé pour cette date.',
    scheduleNewAppointment: 'Planifier un nouveau rendez-vous avec un client.',
    clientName: 'Nom du Client',
    notes: 'Notes',
    optionalNotes: 'Notes facultatives...',
    appointmentDetails: 'Détails du Rendez-vous',
    appointmentAdded: 'Rendez-vous Ajouté',
    appointmentAddedDesc: 'Un nouveau rendez-vous a été programmé.',
    appointmentConfirmed: 'Rendez-vous Confirmé',
    appointmentCancelled: 'Rendez-vous Annulé',
    setWorkingHours: 'Définissez vos heures de travail et le temps tampon entre les rendez-vous.',
    startHour: 'Heure de Début',
    endHour: 'Heure de Fin',
    bufferTime: 'Temps Tampon (minutes)',
    availabilitySaved: 'Disponibilité Enregistrée',
    availabilitySavedDesc: 'Vos heures de travail ont été mises à jour.',
    close: 'Fermer',

    // Dashboard Sections - Projects
    trackProjects: 'Suivez vos services en cours, projets clients et statuts de commandes.',
    currentProjects: 'Projets/Commandes en Cours',
    manageProgress: 'Gérez la progression et le statut de vos engagements clients.',
    searchProjects: 'Rechercher par Client ou Nom de Service...',
    filterByStatus: 'Filtrer par Statut',
    inProgress: 'En Cours',
    completed: 'Terminé',
    scheduled: 'Planifié',
    awaitingFeedback: 'En Attente du Client',
    rejected: 'Rejeté',
    projectId: 'ID du Projet',
    deadline: 'Échéance',
    payment: 'Paiement',
    noProjects: 'Aucun projet ou commande en cours.',
    quickActions: 'Actions Rapides',
    markCompleted: 'Marquer Terminé',
    requestRevision: 'Demander Révision',
    cancelOrder: 'Annuler Commande',
    sendUpdate: 'Envoyer Mise à Jour',
    projectDetails: 'Détails du Projet',
    statusUpdated: 'Statut Mis à Jour',
    projectStatus: 'Statut du projet changé en',
    sendUpdateToClient: 'Envoyer une Mise à Jour au Client',
    typeUpdate: 'Tapez votre message de mise à jour...',
    updateSent: 'Mise à Jour Envoyée',
    updateSentTo: 'Mise à jour envoyée au client pour le projet',

    // Dashboard Sections - Communication
    manageCommunication: 'Gérez vos messages, suivez vos conversations et restez connecté avec vos clients.',
    myConversations: 'Mes Conversations',
    searchMessages: 'Rechercher...',
    selectConversation: 'Sélectionnez une conversation pour commencer à envoyer des messages.',
    realtimeMessaging: 'Messagerie en temps réel avec votre client.',
    typeMessage: 'Tapez votre message...',
    messageSent: 'Message Envoyé',
    conversationArchived: 'Conversation Mise à Jour',
    noConversations: 'Aucune conversation.',

    // Dashboard Sections - Marketing
    boostVisibility: 'Augmentez votre visibilité et attirez plus de clients avec des outils promotionnels.',
    discountCoupons: 'Coupons de Réduction & Codes Promo',
    createManageCoupons: 'Créez et gérez des codes de réduction pour vos services.',
    couponCode: 'Code du Coupon',
    discountType: 'Type de Réduction',
    percentage: 'Pourcentage (%)',
    fixedAmount: 'Montant Fixe (DA)',
    valueAmount: 'Valeur / Montant',
    expiryDate: "Date d'Expiration (Optionnel)",
    usageLimit: "Limite d'Utilisation (0 = illimité)",
    createCoupon: 'Créer un Coupon',
    existingCoupons: 'Coupons Existants',
    code: 'Code',
    discount: 'Réduction',
    usage: 'Utilisation',
    expired: 'Expiré',
    couponCreated: 'Coupon Créé',
    couponDeleted: 'Coupon Supprimé',
    clientTargeting: 'Ciblage Client',
    clientTargetingDesc: 'Outils pour lancer des promotions ciblées vers des segments de clients spécifiques.',

    // Dashboard Sections - Earnings
    trackEarnings: 'Suivez vos revenus, gérez vos factures et demandez des retraits.',
    totalEarned: 'Total Gagné',
    pendingPayout: 'Paiement en Attente',
    platformFees: 'Frais de Plateforme',
    netEarnings: 'Revenus Nets',
    transactionHistory: 'Historique des Transactions & Factures',
    viewPayments: 'Consultez tous les paiements, commissions et générez des factures.',
    description: 'Description',
    type: 'Type',
    amount: 'Montant (DA)',
    invoice: 'Facture',
    exportData: 'Exporter les Données de Revenus',
    withdrawalSystem: 'Système de Retrait',
    requestPayouts: 'Demandez des paiements vers votre compte bancaire ou autres méthodes.',
    currentMethod: 'Méthode de Paiement Actuelle',
    requestWithdrawal: 'Demander un Nouveau Retrait',
    managePayoutMethods: 'Gérer les Méthodes de Paiement',
    commissionNote: 'Les commissions sont calculées automatiquement et déduites avant les paiements. Délai de traitement standard: 3-5 jours ouvrables.',
    enterWithdrawAmount: 'Entrez le montant que vous souhaitez retirer.',
    payoutMethod: 'Méthode de Paiement',
    selectMethod: 'Sélectionner une méthode...',
    submitWithdrawal: 'Soumettre le Retrait',
    withdrawalRequested: 'Retrait Demandé',
    willBeProcessed: 'sera traité sous 3-5 jours ouvrables.',
    addNewMethod: 'Ajouter une Nouvelle Méthode',
    accountDetails: 'Détails du compte (ex: numéro de compte)',
    addMethod: 'Ajouter une Méthode',
    payoutMethodAdded: 'Méthode de Paiement Ajoutée',
    exportComplete: 'Exportation Terminée',
    csvDownloaded: 'Le fichier CSV a été téléchargé.',
    invoiceGenerated: 'Facture Générée',
    downloaded: 'téléchargé',

    // Dashboard Sections - Support
    getHelp: "Obtenez de l'aide, trouvez des réponses et gérez vos demandes de support.",
    submitRequest: 'Soumettre une Nouvelle Demande de Support',
    needHelp: "Besoin d'aide avec la plateforme ou un problème? Dites-le nous.",
    subject: 'Sujet',
    category: 'Catégorie',
    selectCategory: 'Sélectionner la catégorie...',
    technicalIssue: 'Problème Technique',
    billingPayment: 'Facturation/Paiement',
    serviceListing: 'Annonce de Service',
    accountHelp: 'Aide Compte',
    other: 'Autre',
    describeIssue: 'Décrivez votre problème',
    provideDetails: 'Veuillez fournir autant de détails que possible...',
    submitTicket: 'Soumettre le Ticket',
    myTickets: 'Mes Tickets de Support',
    trackTickets: 'Suivez le statut de vos demandes de support soumises.',
    searchTickets: 'Rechercher mes tickets...',
    ticketId: 'ID du Ticket',
    lastUpdate: 'Dernière Mise à Jour',
    open: 'Ouvert',
    resolved: 'Résolu',
    viewReply: 'Voir/Répondre',
    noTickets: "Vous n'avez aucun ticket de support.",
    knowledgeBase: 'Base de Connaissances & FAQ',
    findAnswers: 'Trouvez des réponses aux questions fréquentes et apprenez à utiliser les fonctionnalités.',
    ticketSubmitted: 'Ticket Soumis',
    ticketSubmittedDesc: 'Votre demande de support a été envoyée.',
    originalMessage: 'Message Original',
    you: 'Vous',
    supportTeam: 'Équipe de Support',
    yourReply: 'Votre Réponse',
    typeReply: 'Tapez votre réponse...',
    sendReply: 'Envoyer la Réponse',
    replySent: 'Réponse Envoyée',
    justNow: 'À l\'instant',
    ago: 'passé(s)',

    // AI Refinements
    aiRefinementsTitle: "Besoin d'aide pour affiner votre recherche ?",
    getAiSuggestions: 'Obtenir des Suggestions par IA',
    generatingSuggestions: 'Génération des suggestions...',
    aiRefinementsClickDesc: "Cliquez sur 'Obtenir des Suggestions par IA' pour affiner vos résultats.",
    noRefinementsFound: 'Aucun affinement spécifique trouvé pour cette recherche.',
    errRefinements: 'Impossible de récupérer les suggestions par IA. Veuillez réessayer.',

    // Centralized Notifications
    notificationCenterSub: 'Gérez vos alertes en direct, commandes, réservations, paiements et annonces.',
    notificationPrefSub: 'Personnalisez les canaux et les types d\'alertes reçues.',
    deliveryChannels: 'Canaux de Réception',
    inAppNotif: 'Alertes In-App',
    inAppDesc: 'Notifications contextuelles et tiroir rapide',
    browserPush: 'Notifications Push Navigateur',
    osNotification: 'Push bureau et mobile',
    emailNotif: 'E-mails Récapitulatifs',
    emailDesc: 'Reçus HTML et mises à jour par courriel',
    soundEffects: 'Effets Sonores',
    soundDesc: 'Tonalité sonore lors d\'une nouvelle notification',
    alertCategories: 'Catégories et Activités',
    orderUpdates: 'Commandes et Livraisons',
    orderUpdatesDesc: 'Nouvelles commandes, statut d\'expédition, acceptation et annulation',
    bookingUpdates: 'Réservations de Services et Artisans',
    bookingUpdatesDesc: 'Réservations de créneaux, confirmations et rappels',
    paymentUpdates: 'Paiements, Séquestre et Remboursements',
    paymentUpdatesDesc: 'Dépôts sécurisés, déblocages d\'escrow, remboursements et échecs',
    withdrawalUpdates: 'Retraits Vendeurs et Artisans',
    withdrawalUpdatesDesc: 'Approbation et virement CCP / bancaire des gains',
    messageUpdates: 'Messages et Chat Direct',
    messageUpdatesDesc: 'Messages des clients, vendeurs et prestataires',
    disputesAndReviews: 'Litiges et Avis',
    disputesAndReviewsDesc: 'Dossiers de litige escrow, arbitrage et nouveaux avis',
    verificationUpdates: 'Vérification du Compte et KYC',
    verificationUpdatesDesc: 'Approbation du badge certifié ou demande de justificatifs',
    adminAnnouncements: 'Annonces Khidmatik Officielles',
    announcementsDesc: 'Mises à jour plateforme, nouveaux services et informations',
    clearRead: 'Effacer les lus',
    savePreferences: 'Enregistrer les préférences',
    allNotifications: 'Toutes les notifications',
    noUnreadNotifications: 'Aucune notification non lue',
    noNotificationsYet: 'Aucune notification pour le moment',
    notificationsAutoDesc: 'Vos commandes, réservations, paiements et mises à jour système apparaîtront ici en direct.',
    noNotificationsFound: 'Aucune notification correspondante trouvée',
    tryDifferentSearch: 'Essayez d\'ajuster vos termes de recherche ou de réinitialiser les filtres.',
    notificationCenterEmptyDesc: 'Vous êtes à jour ! Vos prochaines notifications apparaîtront ici.',
    clearSearch: 'Effacer la recherche',
    simulateEvent: 'Tester les Alertes (17 Types)',
    unreadOnly: 'Non lues',
    readOnly: 'Lues',
    searchNotifications: 'Rechercher dans les notifications...',

    // Real-Time Messaging System
    attachImage: 'Joindre une Image',
    attachFile: 'Joindre un Fichier',
    all: 'Tous',
    online: 'En ligne',
    offline: 'Hors ligne',
    storeOwner: 'Commerçant',
    serviceProvider: 'Prestataire',
    supportAgent: 'Agent de Support',
    customer: 'Client',
    reportUser: 'Signaler l\'utilisateur',
    blockUser: 'Bloquer l\'utilisateur',
    unblockUser: 'Débloquer l\'utilisateur',
    startConversation: 'Démarrer une conversation',
    startConversationDesc: 'Envoyez un message ou une pièce jointe pour échanger directement.',
    replyingTo: 'En réponse à',
    noConversationsYet: 'Aucune conversation pour le moment.',
    noMessagesYet: 'Aucun message pour le moment.',
    openMessagingHub: 'Ouvrir le Centre de Messagerie',
    chatBlockedWarning: 'Cette conversation est bloquée. Vous ne pouvez ni envoyer ni recevoir de messages.',
    viewListing: 'Voir l\'annonce / le contexte',
    reportSubmitted: 'Signalement Envoyé',
    reportSubmittedDesc: 'Merci. Notre équipe examinera ce signalement sous 24 heures.',
    userBlocked: 'Utilisateur Bloqué',
    userBlockedDesc: 'Cet utilisateur ne pourra plus vous envoyer de messages.',
    userUnblocked: 'Utilisateur Débloqué',
    userUnblockedDesc: 'Vous pouvez désormais échanger des messages avec cet utilisateur.',
    selectConversationDesc: 'Choisissez une discussion dans la barre latérale ou démarrez un échange depuis une fiche magasin ou artisan.',

    // Upgraded Review & Rating System
    basedOn: 'Basé sur',
    verifiedReviews: 'avis vérifiés',
    verifiedPurchases: 'Achats Vérifiés',
    verifiedPurchase: 'Achat Vérifié',
    verifiedReview: 'Avis Client Vérifié',
    writeAReview: 'Rédiger un Avis Vérifié',
    ratingDistribution: 'Répartition des Notes',
    clearStarFilter: 'Afficher toutes les notes',
    detailedCriteria: 'Critères d\'Évaluation',
    criteria_quality: 'Qualité du Travail / Produits',
    criteria_price: 'Prix & Rapport Qualité/Prix',
    criteria_communication: 'Communication & Réactivité',
    criteria_punctuality: 'Ponctualité & Rapidité',
    criteria_professionalism: 'Professionnalisme & Expertise',
    viewCriteriaRatings: 'Détail des notes par critère',
    sellerResponse: 'Réponse du Prestataire',
    helpful: 'Utile',
    reply: 'Répondre',
    report: 'Signaler',
    rateAndReview: 'Évaluer & Donner un avis sur',
    writeReviewDesc: 'Partagez votre expérience vérifiée avec une évaluation détaillée multicritères.',
    selectOrderToReview: 'Sélectionnez la commande ou prestation terminée',
    overallRating: 'Note Globale',
    rateSpecificAspects: 'Évaluation des Critères Spécifiques',
    reviewTitle: 'Titre de l\'avis (Optionnel)',
    reviewTitlePlaceholder: 'Ex: Excellent service, travail soigné et rapide !',
    detailedReview: 'Avis détaillé',
    detailedReviewPlaceholder: 'Qu\'avez-vous apprécié ? Comment était la qualité, la communication et la livraison ?',
    addPhotosVideos: 'Ajouter des photos ou vidéos (Optionnel)',
    uploadMedia: 'Importer des médias',
    mediaUploadHint: 'Importez jusqu\'à 6 photos ou vidéos haute résolution.',
    publishReview: 'Publier l\'Avis Vérifié',
    officialResponse: 'Réponse Officielle du Prestataire',
    replyToCustomer: 'Répondre au client',
    replyDesc: 'Votre réponse publique sera épinglée directement sous l\'avis du client.',
    yourResponse: 'Votre Réponse',
    replyPlaceholder: 'Merci pour votre confiance et vos retours chaleureux...',
    postResponse: 'Publier la Réponse',
    reportThisReview: 'Signaler un avis inapproprié',
    reportReviewDesc: 'Aidez-nous à préserver l\'authenticité de Khidmatik. Les signalements sont traités sous 24h.',
    selectViolationReason: 'Sélectionnez le motif du signalement',
    additionalDetails: 'Détails complémentaires (Optionnel)',
    reportDetailsPlaceholder: 'Apportez des précisions pour notre équipe de modération...',
    submitReport: 'Envoyer le Signalement',
    verifiedOnly: 'Vérifiés uniquement',
    withPhotosVideos: 'Avec photos & vidéos',
    searchReviews: 'Rechercher dans les avis...',
    mostRecent: 'Plus récents',
    highestRating: 'Meilleures notes',
    lowestRating: 'Moins bonnes notes',
    mostHelpful: 'Plus utiles',
    loadingReviews: 'Chargement des avis vérifiés...',
    noReviewsFound: 'Aucun avis ne correspond à vos filtres',
    beTheFirstReview: 'Avez-vous effectué une commande ou prestation ici ? Partagez votre avis vérifié.',
    showLess: 'Voir moins',
    readMore: 'Lire la suite',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en'); // Default to English

  useEffect(() => {
    const storedLanguage = typeof window !== 'undefined' ? localStorage.getItem('khidmatik-lang') as Language | null : null;
    if (storedLanguage && ['en', 'ar', 'fr'].includes(storedLanguage)) {
      setLanguageState(storedLanguage);
      document.documentElement.lang = storedLanguage;
      document.documentElement.dir = storedLanguage === 'ar' ? 'rtl' : 'ltr';
    } else {
      document.documentElement.lang = 'en';
      document.documentElement.dir = 'ltr';
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('khidmatik-lang', lang);
    }
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const translate = (key: string, defaultText: string): string => {
    return translations[language]?.[key] || defaultText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

    